//! `#[repr(C)]` mirrors of the `marmot-uniffi` conversion types.
//!
//! One module per `marmot-uniffi` conversions module, same names. Plain
//! records and fieldless enums are generated by the macros in
//! [`crate::macros`]; enums with payloads (C tagged unions) are written by
//! hand. Field order matches the Ffi definitions, so the C layout follows
//! the documented Swift/Kotlin surface.

pub mod account;
pub mod agent_stream;
pub mod audit;
pub mod chat_list;
pub mod common;
pub mod event;
pub mod group;
pub mod markdown;
pub mod media;
pub mod message;
pub mod notification;
pub mod push;
pub mod relay;
pub mod timeline;
