//! Closed built-in event catalogue. Host observations cannot register these names.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ProductFamily {
    Runtime,
    Account,
    KeyPackage,
    Group,
    Welcome,
    MessageAction,
    MessageProcessing,
    Media,
    Directory,
    Notification,
    Sync,
    Connectivity,
    Recovery,
    Maintenance,
    Storage,
    Agent,
    Stream,
}
impl ProductFamily {
    pub const ALL: &'static [Self] = &[
        Self::Runtime,
        Self::Account,
        Self::KeyPackage,
        Self::Group,
        Self::Welcome,
        Self::MessageAction,
        Self::MessageProcessing,
        Self::Media,
        Self::Directory,
        Self::Notification,
        Self::Sync,
        Self::Connectivity,
        Self::Recovery,
        Self::Maintenance,
        Self::Storage,
        Self::Agent,
        Self::Stream,
    ];
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Runtime => "mdk_runtime_summary",
            Self::Account => "mdk_account_summary",
            Self::KeyPackage => "mdk_key_package_summary",
            Self::Group => "mdk_group_summary",
            Self::Welcome => "mdk_welcome_summary",
            Self::MessageAction => "mdk_message_action_summary",
            Self::MessageProcessing => "mdk_message_processing_summary",
            Self::Media => "mdk_media_summary",
            Self::Directory => "mdk_directory_summary",
            Self::Notification => "mdk_notification_summary",
            Self::Sync => "mdk_sync_summary",
            Self::Connectivity => "mdk_connectivity_summary",
            Self::Recovery => "mdk_recovery_summary",
            Self::Maintenance => "mdk_maintenance_summary",
            Self::Storage => "mdk_storage_summary",
            Self::Agent => "mdk_agent_summary",
            Self::Stream => "mdk_stream_summary",
        }
    }
    pub fn operations(self) -> &'static [&'static str] {
        match self {
            Self::Runtime => &[
                "startup",
                "resume",
                "readiness",
                "catch_up",
                "shutdown",
                "coverage",
                "overflow",
            ],
            Self::Account => &[
                "create",
                "import",
                "external_signer",
                "login",
                "logout",
                "switch",
                "profile_update",
                "local_ready",
                "network_ready",
            ],
            Self::KeyPackage => &["generate", "publish", "rotate", "retire", "lookup"],
            Self::Group => &[
                "create",
                "accept_invite",
                "decline_invite",
                "invite",
                "remove_members",
                "leave",
                "delete",
                "archive",
                "unarchive",
                "profile_update",
                "image_update",
                "promote_admin",
                "demote_admin",
                "disband",
                "retention",
            ],
            Self::Welcome => &["publish", "retry", "process"],
            Self::MessageAction => &[
                "text",
                "reply",
                "reaction",
                "unreact",
                "edit",
                "delete",
                "media",
                "custom",
                "publication",
            ],
            Self::MessageProcessing => &[
                "receive",
                "duplicate",
                "deferred",
                "invalidation",
                "failure",
            ],
            Self::Media => &[
                "upload",
                "download",
                "cancel",
                "cache_hit",
                "failover",
                "integrity",
                "decrypt",
                "group_image",
            ],
            Self::Directory => &[
                "profile",
                "follows",
                "relay_list",
                "key_package",
                "search",
                "follow",
                "unfollow",
                "publish",
            ],
            Self::Notification => &[
                "register", "update", "remove", "trigger", "schedule", "mute", "unmute", "enable",
                "disable",
            ],
            Self::Sync => &[
                "initial",
                "foreground",
                "background",
                "reconnect",
                "full_history",
            ],
            Self::Connectivity => &["availability", "connect", "reconnect", "publish_quorum"],
            Self::Recovery => &[
                "quarantine",
                "hydration",
                "invalidation",
                "revalidation",
                "unrecoverable",
                "pending_commit",
                "convergence",
                "backfill",
                "overflow",
            ],
            Self::Maintenance => &[
                "sweep",
                "self_update",
                "key_package",
                "retention",
                "deferred",
                "capacity",
                "pending",
                "catch_up",
                "ambiguous",
                "failed",
            ],
            Self::Storage => &[
                "open",
                "migration",
                "recovery",
                "corruption",
                "capacity",
                "busy",
                "close",
            ],
            Self::Agent => &[
                "bootstrap",
                "readiness",
                "control",
                "control_read",
                "control_write",
                "control_preview",
                "final_message",
                "replay",
                "invite_policy",
            ],
            Self::Stream => &[
                "start",
                "watch",
                "finalize",
                "cancel",
                "first_preview",
                "disconnect",
                "overflow",
                "integrity",
            ],
        }
    }
}
#[derive(Clone, Copy, Debug)]
pub enum ProductUnit {
    Action,
    Attempt,
    Transition,
    Coverage,
}
impl ProductUnit {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Action => "action",
            Self::Attempt => "attempt",
            Self::Transition => "transition",
            Self::Coverage => "coverage",
        }
    }
}
pub const PRODUCT_OUTCOMES: &[&str] = &[
    "success",
    "failure",
    "pending",
    "confirmed",
    "unknown",
    "rejected",
    "deferred",
    "no_work_due",
    "performed",
    "cancelled",
    "timeout",
    "network",
    "storage",
    "capacity",
    "invalid",
    "unsupported",
    "not_ready",
    "empty",
    "cache",
    "none",
    "partial",
    "available",
    "duplicate",
    "usable",
    "absent",
    "expired",
    "unavailable",
];
