/* Generated by cbindgen — do not edit manually.
 *
 * mdk-cbindings: C ABI bindings for mdk-core
 * https://github.com/marmot-protocol/mdk
 */

#ifndef MDK_H
#define MDK_H

/* Warning: this file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes returned by all fallible C API functions.
 */
typedef enum MdkError {
    /**
     * Success — no error.
     */
    MDK_ERROR_OK = 0,
    /**
     * Storage-layer error (SQLite, I/O, etc.).
     */
    MDK_ERROR_STORAGE = 1,
    /**
     * MDK core error (MLS, protocol, crypto).
     */
    MDK_ERROR_MDK = 2,
    /**
     * Invalid input from the caller (bad hex, bad JSON, wrong byte length, etc.).
     */
    MDK_ERROR_INVALID_INPUT = 3,
    /**
     * A required pointer argument was null.
     */
    MDK_ERROR_NULL_POINTER = 4,
} MdkError;

/**
 * Opaque handle to an MDK instance, passed across the FFI boundary as a pointer.
 *
 * The inner [`MDK`] is wrapped in a [`Mutex`] for thread safety, mirroring
 * the UniFFI crate's approach.
 */
typedef struct MdkHandle MdkHandle;

/**
 * Create a new MDK instance with encrypted SQLite storage using automatic
 * key management (platform keyring).
 *
 * # Parameters
 *
 * * `db_path`      — Null-terminated path to the SQLite database file.
 * * `service_id`   — Stable, host-defined application identifier.
 * * `db_key_id`    — Stable identifier for this database's key.
 * * `config_json`  — Optional JSON config (null → defaults).
 * * `out`          — On success, receives a pointer to the new handle.
 *
 * # Safety
 *
 * All pointer arguments (except `config_json`, which may be null) must be
 * valid, null-terminated C strings.  `out` must be a valid, non-null pointer.
 */

enum MdkError mdk_new(const char *db_path,
                      const char *service_id,
                      const char *db_key_id,
                      const char *config_json,
                      struct MdkHandle **out)
;

/**
 * Create a new MDK instance with encrypted SQLite storage using a directly
 * provided 32-byte key.
 *
 * # Safety
 *
 * `key` must point to at least `key_len` readable bytes.  Other pointer
 * arguments follow the same rules as [`mdk_new`].
 */

enum MdkError mdk_new_with_key(const char *db_path,
                               const uint8_t *key,
                               uintptr_t key_len,
                               const char *config_json,
                               struct MdkHandle **out)
;

/**
 * Create a new MDK instance with **unencrypted** SQLite storage.
 *
 * **WARNING**: Sensitive MLS state including exporter secrets will be stored
 * in plaintext. Only use for development or testing.
 *
 * # Safety
 *
 * Same rules as [`mdk_new`]. `config_json` may be null.
 */

enum MdkError mdk_new_unencrypted(const char *db_path,
                                  const char *config_json,
                                  struct MdkHandle **out)
;

/**
 * Free an MDK handle previously returned by one of the constructors.
 *
 * After calling this, the handle pointer is invalid and must not be used.
 * Passing null is a safe no-op.
 *
 * # Safety
 *
 * `handle` must be a pointer previously returned by `mdk_new`,
 * `mdk_new_with_key`, or `mdk_new_unencrypted` (or null).
 */
 void mdk_free(struct MdkHandle *handle) ;

/**
 * Retrieve the last error message from the **calling thread**.
 *
 * Returns a heap-allocated C string that the caller **must** free with
 * `mdk_string_free`. Returns null if no
 * error has been recorded on this thread.
 *
 * **Important**: Error messages are thread-local. You must call this from the
 * same thread that received the error code. In callback-based architectures
 * where the call and the error check happen on different threads, the message
 * will not be available.
 *
 * # Safety
 *
 * The returned pointer is valid until freed. Calling this function clears
 * the stored message — a second call without an intervening error returns null.
 */
 char *mdk_last_error_message(void) ;

/**
 * Free a string previously returned by any `mdk_*` function.
 *
 * # Safety
 *
 * `s` must be a pointer previously returned by an `mdk_*` function, or null
 * (in which case this is a no-op). Passing any other pointer is undefined
 * behaviour. Do **not** call this more than once on the same pointer.
 */
 void mdk_string_free(char *s) ;

/**
 * Free a byte array previously returned by an `mdk_*` function.
 *
 * Handles zero-length allocations correctly — `Box::from_raw` with a
 * zero-length slice is valid in Rust, so `len == 0` with a non-null
 * `data` will still free the allocation.
 *
 * # Safety
 *
 * `data` must be a pointer previously returned by an `mdk_*` function (paired
 * with the correct `len`), or null (no-op). Passing any other pointer or an
 * incorrect length is undefined behaviour.
 */
 void mdk_bytes_free(uint8_t *data, uintptr_t len) ;

/**
 * Get all groups as a JSON array.
 *
 * # Safety
 *
 * `h` must be a valid handle. `out_json` must not be null.
 */
 enum MdkError mdk_get_groups(struct MdkHandle *h, char **out_json) ;

/**
 * Get a single group by MLS group ID (hex).
 *
 * On success, `*out_json` receives the group JSON or `"null"` if not found.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */
 enum MdkError mdk_get_group(struct MdkHandle *h, const char *mls_group_id, char **out_json) ;

/**
 * Get members of a group as a JSON array of hex-encoded public keys.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */
 enum MdkError mdk_get_members(struct MdkHandle *h, const char *mls_group_id, char **out_json) ;

/**
 * Get group IDs that need a self-update, as a JSON array of hex strings.
 *
 * # Parameters
 *
 * * `threshold_secs` — Groups whose last rotation is older than this are included.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */

enum MdkError mdk_groups_needing_self_update(struct MdkHandle *h,
                                             uint64_t threshold_secs,
                                             char **out_json)
;

/**
 * Create a new group.
 *
 * # Parameters
 *
 * * `creator_pk`          — Hex-encoded creator public key.
 * * `key_packages_json`   — JSON array of key-package event objects.
 * * `name`                — Group name.
 * * `description`         — Group description.
 * * `relays_json`         — JSON array of relay URL strings.
 * * `admins_json`         — JSON array of admin public key hex strings.
 * * `out_json`            — On success, receives a `CreateGroupResult` JSON.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */

enum MdkError mdk_create_group(struct MdkHandle *h,
                               const char *creator_pk,
                               const char *key_packages_json,
                               const char *name,
                               const char *description,
                               const char *relays_json,
                               const char *admins_json,
                               char **out_json)
;

/**
 * Add members to a group.
 *
 * # Parameters
 *
 * * `key_packages_json` — JSON array of key-package event objects.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */

enum MdkError mdk_add_members(struct MdkHandle *h,
                              const char *mls_group_id,
                              const char *key_packages_json,
                              char **out_json)
;

/**
 * Remove members from a group.
 *
 * # Parameters
 *
 * * `pubkeys_json` — JSON array of hex-encoded public key strings.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */

enum MdkError mdk_remove_members(struct MdkHandle *h,
                                 const char *mls_group_id,
                                 const char *pubkeys_json,
                                 char **out_json)
;

/**
 * Update group data (name, description, image, relays, admins).
 *
 * # Parameters
 *
 * * `update_json` — JSON object with optional fields: `name`, `description`,
 *   `image_hash`, `image_key`, `image_nonce`, `relays`, `admins`.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */

enum MdkError mdk_update_group_data(struct MdkHandle *h,
                                    const char *mls_group_id,
                                    const char *update_json,
                                    char **out_json)
;

/**
 * Perform a self-update (key rotation) for a group.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */
 enum MdkError mdk_self_update(struct MdkHandle *h, const char *mls_group_id, char **out_json) ;

/**
 * Create a proposal to leave the group.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */
 enum MdkError mdk_leave_group(struct MdkHandle *h, const char *mls_group_id, char **out_json) ;

/**
 * Merge pending commit for a group.
 *
 * # Safety
 *
 * `h` and `mls_group_id` must be valid.
 */
 enum MdkError mdk_merge_pending_commit(struct MdkHandle *h, const char *mls_group_id) ;

/**
 * Clear pending commit for a group (rollback to pre-commit state).
 *
 * # Safety
 *
 * `h` and `mls_group_id` must be valid.
 */
 enum MdkError mdk_clear_pending_commit(struct MdkHandle *h, const char *mls_group_id) ;

/**
 * Sync group metadata from MLS state.
 *
 * # Safety
 *
 * `h` and `mls_group_id` must be valid.
 */
 enum MdkError mdk_sync_group_metadata(struct MdkHandle *h, const char *mls_group_id) ;

/**
 * Get relays for a group as a JSON array of URL strings.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */
 enum MdkError mdk_get_relays(struct MdkHandle *h, const char *mls_group_id, char **out_json) ;

/**
 * Create a key package for a Nostr event.
 *
 * Does **not** add the NIP-70 protected tag for maximum relay compatibility.
 * Use [`mdk_create_key_package_with_options`] if you need the protected tag.
 *
 * On success, `*out_json` receives a JSON object with fields
 * `key_package`, `tags`, and `hash_ref`.
 *
 * # Safety
 *
 * All pointer arguments must be valid.  `out_json` must not be null.
 */

enum MdkError mdk_create_key_package(struct MdkHandle *h,
                                     const char *pubkey,
                                     const char *relays_json,
                                     char **out_json)
;

/**
 * Create a key package for a Nostr event with additional options.
 *
 * # Parameters
 *
 * * `protected_` — When `true`, adds the NIP-70 protected tag.
 *
 * # Safety
 *
 * Same as [`mdk_create_key_package`].
 */

enum MdkError mdk_create_key_package_with_options(struct MdkHandle *h,
                                                  const char *pubkey,
                                                  const char *relays_json,
                                                  bool protected_,
                                                  char **out_json)
;

/**
 * Parse a key package from a Nostr event.
 *
 * On success, `*out` receives the key-package content string (the event's
 * `content` field, after validation).
 *
 * # Safety
 *
 * All pointer arguments must be valid. `out` must not be null.
 */
 enum MdkError mdk_parse_key_package(struct MdkHandle *h, const char *event_json, char **out) ;

/**
 * Prepare a group image for upload to Blossom.
 *
 * Encrypts the image and returns the encrypted data together with the
 * encryption key and metadata as a JSON string.  The returned JSON does
 * **not** include the upload secret key — callers must derive the upload
 * keypair separately via [`mdk_derive_upload_keypair`] using the
 * `image_key` from the returned JSON.
 *
 * # Parameters
 *
 * * `data`     — Raw image bytes.
 * * `len`      — Length of `data`.
 * * `mime`     — MIME type (e.g. `"image/png"`).
 * * `out_json` — Receives a JSON object with encrypted data and metadata.
 *
 * # Safety
 *
 * `data` must point to at least `len` readable bytes. Other pointer
 * arguments must be valid.
 */

enum MdkError mdk_prepare_group_image(const uint8_t *data,
                                      uintptr_t len,
                                      const char *mime,
                                      char **out_json)
;

/**
 * Decrypt a group image.
 *
 * # Parameters
 *
 * * `data` / `data_len` — Encrypted image data.
 * * `hash` / `hash_len` — Expected SHA-256 hash (32 bytes), or null to skip verification.
 * * `key` / `key_len`   — 32-byte encryption key.
 * * `nonce` / `nonce_len` — 12-byte nonce.
 * * `out` / `out_len`   — On success, receives the decrypted image bytes
 *   (caller must free with `mdk_bytes_free`).
 *
 * # Safety
 *
 * All data pointers must point to at least their corresponding `*_len` bytes.
 * `hash` may be null (no hash verification). `out` and `out_len` must be valid.
 */

enum MdkError mdk_decrypt_group_image(const uint8_t *data,
                                      uintptr_t data_len,
                                      const uint8_t *hash,
                                      uintptr_t hash_len,
                                      const uint8_t *key,
                                      uintptr_t key_len,
                                      const uint8_t *nonce,
                                      uintptr_t nonce_len,
                                      uint8_t **out,
                                      uintptr_t *out_len)
;

/**
 * Derive an upload keypair from an image key.
 *
 * Returns the secret key as a hex string.
 *
 * # Parameters
 *
 * * `key` / `key_len` — 32-byte image encryption key.
 * * `version`         — Version number for key derivation.
 * * `out`             — Receives a hex-encoded secret key string.
 *
 * # Safety
 *
 * `key` must point to at least `key_len` bytes. `out` must be valid.
 */

enum MdkError mdk_derive_upload_keypair(const uint8_t *key,
                                        uintptr_t key_len,
                                        uint16_t version,
                                        char **out)
;

/**
 * Create a message in a group.
 *
 * # Parameters
 *
 * * `mls_group_id` — Hex-encoded MLS group ID.
 * * `sender_pk`    — Hex-encoded sender public key.
 * * `content`      — Message content string.
 * * `kind`         — Nostr event kind (numeric).
 * * `tags_json`    — Optional JSON array of tag arrays, e.g.
 *   `[["p","hex..."],["e","hex..."]]`. Pass null for no tags.
 * * `out_json`     — On success, receives the serialised Nostr event JSON.
 *
 * # Safety
 *
 * All non-null pointer arguments must be valid C strings.
 */

enum MdkError mdk_create_message(struct MdkHandle *h,
                                 const char *mls_group_id,
                                 const char *sender_pk,
                                 const char *content,
                                 uint16_t kind,
                                 const char *tags_json,
                                 char **out_json)
;

/**
 * Process an incoming MLS message.
 *
 * On success, `*out_json` receives a tagged-union JSON object with a `"type"`
 * field indicating the result variant (e.g. `"ApplicationMessage"`,
 * `"Proposal"`, `"PendingProposal"`, `"Commit"`, etc.).
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */
 enum MdkError mdk_process_message(struct MdkHandle *h, const char *event_json, char **out_json) ;

/**
 * Get messages for a group with optional pagination.
 *
 * # Parameters
 *
 * * `limit`      — Maximum number of messages (0 = no limit / default 1000).
 * * `offset`     — Number of messages to skip (0 = none).
 * * `sort_order` — Optional: `"created_at_first"` or `"processed_at_first"`.
 *   Null = default (`created_at_first`).
 *
 * On success, `*out_json` receives a JSON array of message objects.
 *
 * # Safety
 *
 * All pointer arguments must be valid. `sort_order` may be null.
 */

enum MdkError mdk_get_messages(struct MdkHandle *h,
                               const char *mls_group_id,
                               uint32_t limit,
                               uint32_t offset,
                               const char *sort_order,
                               char **out_json)
;

/**
 * Get a single message by event ID within a group.
 *
 * On success, `*out_json` receives the message JSON or `"null"`.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */

enum MdkError mdk_get_message(struct MdkHandle *h,
                              const char *mls_group_id,
                              const char *event_id,
                              char **out_json)
;

/**
 * Get the most recent message in a group under the given sort order.
 *
 * # Parameters
 *
 * * `sort_order` — Required: `"created_at_first"` or `"processed_at_first"`.
 *
 * # Safety
 *
 * All pointer arguments must be valid. `sort_order` must not be null.
 */

enum MdkError mdk_get_last_message(struct MdkHandle *h,
                                   const char *mls_group_id,
                                   const char *sort_order,
                                   char **out_json)
;

/**
 * Get pending welcomes with optional pagination.
 *
 * # Parameters
 *
 * * `limit`  — Maximum number of welcomes (0 = no limit / default 1000).
 * * `offset` — Number of welcomes to skip (0 = none).
 *
 * On success, `*out_json` receives a JSON array of welcome objects.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */

enum MdkError mdk_get_pending_welcomes(struct MdkHandle *h,
                                       uint32_t limit,
                                       uint32_t offset,
                                       char **out_json)
;

/**
 * Get a welcome by event ID.
 *
 * On success, `*out_json` receives the welcome JSON or `"null"`.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */
 enum MdkError mdk_get_welcome(struct MdkHandle *h, const char *event_id, char **out_json) ;

/**
 * Process a welcome message.
 *
 * # Parameters
 *
 * * `wrapper_event_id` — Hex-encoded event ID of the 1059 wrapper event.
 * * `rumor_json`       — JSON of the rumor (kind 444) unsigned event.
 *
 * On success, `*out_json` receives the processed welcome as JSON.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */

enum MdkError mdk_process_welcome(struct MdkHandle *h,
                                  const char *wrapper_event_id,
                                  const char *rumor_json,
                                  char **out_json)
;

/**
 * Accept a welcome message.
 *
 * # Parameters
 *
 * * `welcome_json` — JSON representation of the welcome (as returned by
 *   [`mdk_process_welcome`] or [`mdk_get_welcome`]).
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */
 enum MdkError mdk_accept_welcome(struct MdkHandle *h, const char *welcome_json) ;

/**
 * Decline a welcome message.
 *
 * # Parameters
 *
 * * `welcome_json` — JSON representation of the welcome.
 *
 * # Safety
 *
 * All pointer arguments must be valid.
 */
 enum MdkError mdk_decline_welcome(struct MdkHandle *h, const char *welcome_json) ;

#endif  /* MDK_H */
