//! `extern "C"` command wrappers over `marmot_uniffi::Marmot`.
//!
//! Every wrapper follows the same shape, so almost all of them are
//! generated by [`c_cmd!`]:
//!
//! - `ffi_guard` around the body (no unwinding into C).
//! - Borrowed inputs read with `required_str` / `optional_str` /
//!   `str_array` / input-struct `to_ffi`; caller memory is never freed.
//! - Async runtime methods run via `client.block_on`.
//! - Results convert to `#[repr(C)]` mirrors, move to the heap, and are
//!   written through the out-pointer; the caller releases them with the
//!   type's `marmot_*_free`.
//! - Errors map through `status::status_from_error`.
//!
//! Commands with struct/byte inputs are written by hand below the macro
//! block.

use std::ffi::c_char;

use marmot_uniffi::MarmotKitError;

use crate::MarmotStatus;
use crate::memory::{CFree, boxed, owned_c_string, required_str, str_array};
use crate::status::status_from_error;
use crate::types::account::{
    MarmotAccountKeyPackageList, MarmotAccountSetupReadiness, MarmotAccountSummary,
    MarmotAccountSummaryList, MarmotAccountUnreadList, MarmotIdentityCreationResult,
    MarmotSendSummary, MarmotSignOutOutcome, MarmotUserProfileMetadata, MarmotWipeOutcome,
};
use crate::types::agent_stream::MarmotAgentStreamStart;
use crate::types::audit::{
    MarmotAuditLogDeleteResult, MarmotAuditLogFileList, MarmotAuditLogSettings,
    MarmotAuditLogTrackerConfig, MarmotAuditLogTrackerUpdateResult, MarmotAuditLogUploadResult,
};
use crate::types::chat_list::{
    MarmotChatListRow, MarmotChatListRowList, MarmotChatNotificationSettings, MarmotChatPinState,
    MarmotExistingDirectConversation,
};
use crate::types::common::{MarmotMessageTag, MarmotStringArray, MarmotStringList};
use crate::types::directory::MarmotCachedIdentityProjectionList;
use crate::types::draft::MarmotMessageDraftAttachmentInput;
use crate::types::draft::{MarmotMessageDraft, MarmotMessageDraftSummaryList};
use crate::types::group::{
    MarmotAppBlobEndpoint, MarmotAppGroupMemberIdsList, MarmotAppGroupMemberRecordList,
    MarmotAppGroupMlsState, MarmotAppGroupRecord, MarmotAppQuarantinedGroupList,
    MarmotCreateGroupOptions, MarmotCreatedGroup, MarmotDisbandRequest,
    MarmotGroupConversationSnapshot, MarmotGroupDetails, MarmotGroupInviteDeclineResult,
    MarmotGroupManagementState, MarmotGroupMutationResult, MarmotGroupRoster,
    MarmotInitialGroupImage, MarmotMemberKeyPackagePrewarmSummary, MarmotMemberRef,
    MarmotPreparedGroupImageUpload, MarmotPreparedGroupImageUploadList,
};
use crate::types::maintenance::{
    MarmotGroupMaintenanceStatus, MarmotKeyPackageMaintenanceStatus, MarmotMaintenanceRunSummary,
    MarmotPeriodicMaintenancePolicy,
};
use crate::types::markdown::MarmotMarkdownDocument;
use crate::types::media::{
    MarmotMediaAttachmentReference, MarmotMediaDownloadResult, MarmotMediaRecordList,
    MarmotMediaUploadRequest, MarmotMediaUploadResult,
};
use crate::types::message::{
    MarmotAppMessageRecordList, MarmotRetentionSweepReport, MarmotSecureDeleteExpiredResult,
};
use crate::types::notification::{
    MarmotBackgroundNotificationCollection, MarmotNotificationSettings,
    MarmotNotificationWakeSource,
};
use crate::types::push::{
    MarmotGroupPushDebugInfo, MarmotPushPlatform, MarmotPushRegistration,
    MarmotPushRegistrationShareOutcome, MarmotPushRegistrationSyncResult,
};
use crate::types::relay::{
    MarmotAccountRelayLists, MarmotRelayEndpointClassificationList, MarmotRelayHealth,
    MarmotRelayTelemetryRuntimeConfig, MarmotRelayTelemetrySettings,
};
use crate::types::telemetry::{
    MarmotAppPerformanceSnapshot, MarmotHostPerformanceOperation, MarmotHostPerformanceOutcome,
};
use crate::types::timeline::{MarmotTimelineMessageQuery, MarmotTimelinePage};
use crate::{MarmotClient, client_ref, ffi_guard, write_out};

/// Shorthand used by every command wrapper: validate + read an argument,
/// or return the argument's status code from the enclosing function.
macro_rules! try_arg {
    ($expr:expr) => {
        match $expr {
            Ok(value) => value,
            Err(status) => return status,
        }
    };
}
pub(crate) use try_arg;

/// Deliver a fallible record result: convert to the mirror, move it to
/// the heap, write it through the out-pointer.
pub(crate) unsafe fn deliver<TFfi, TMirror>(
    result: Result<TFfi, MarmotKitError>,
    out: *mut *mut TMirror,
) -> MarmotStatus
where
    TMirror: From<TFfi> + CFree,
{
    match result {
        Ok(value) => {
            let root = boxed(TMirror::from(value));
            match unsafe { write_out(out, root) } {
                Ok(()) => MarmotStatus::Ok,
                Err(status) => {
                    unsafe { crate::memory::free_boxed(root) };
                    status
                }
            }
        }
        Err(err) => status_from_error(&err),
    }
}

/// Deliver a fallible `Option<record>` result: `None` writes NULL and
/// still returns `MARMOT_STATUS_OK` — callers distinguish "absent" from
/// failure by the status code.
pub(crate) unsafe fn deliver_opt<TFfi, TMirror>(
    result: Result<Option<TFfi>, MarmotKitError>,
    out: *mut *mut TMirror,
) -> MarmotStatus
where
    TMirror: From<TFfi> + CFree,
{
    match result {
        Ok(value) => {
            let root = value.map_or(std::ptr::null_mut(), |v| boxed(TMirror::from(v)));
            match unsafe { write_out(out, root) } {
                Ok(()) => MarmotStatus::Ok,
                Err(status) => {
                    unsafe { crate::memory::free_boxed(root) };
                    status
                }
            }
        }
        Err(err) => status_from_error(&err),
    }
}

/// Deliver a fallible scalar result (u64/bool/...) by value.
pub(crate) unsafe fn deliver_scalar<T>(
    result: Result<T, MarmotKitError>,
    out: *mut T,
) -> MarmotStatus {
    match result {
        Ok(value) => match unsafe { write_out(out, value) } {
            Ok(()) => MarmotStatus::Ok,
            Err(status) => status,
        },
        Err(err) => status_from_error(&err),
    }
}

/// Deliver a fallible `String` result as an owned C string.
pub(crate) unsafe fn deliver_string(
    result: Result<String, MarmotKitError>,
    out: *mut *mut c_char,
) -> MarmotStatus {
    match result {
        Ok(value) => {
            let ptr = owned_c_string(value);
            match unsafe { write_out(out, ptr) } {
                Ok(()) => MarmotStatus::Ok,
                Err(status) => {
                    unsafe { crate::memory::free_c_string(ptr) };
                    status
                }
            }
        }
        Err(err) => status_from_error(&err),
    }
}

/// Deliver a fallible fieldless-enum result by value.
pub(crate) unsafe fn deliver_enum<TFfi, TMirror>(
    result: Result<TFfi, MarmotKitError>,
    out: *mut TMirror,
) -> MarmotStatus
where
    TMirror: From<TFfi>,
{
    match result {
        Ok(value) => match unsafe { write_out(out, TMirror::from(value)) } {
            Ok(()) => MarmotStatus::Ok,
            Err(status) => status,
        },
        Err(err) => status_from_error(&err),
    }
}

/// Deliver a fallible `Option<String>` result: `None` writes NULL and
/// still returns `MARMOT_STATUS_OK` — callers distinguish "absent" from
/// failure by the status code.
pub(crate) unsafe fn deliver_opt_string(
    result: Result<Option<String>, MarmotKitError>,
    out: *mut *mut c_char,
) -> MarmotStatus {
    match result {
        Ok(value) => {
            let ptr = crate::memory::owned_opt_c_string(value);
            match unsafe { write_out(out, ptr) } {
                Ok(()) => MarmotStatus::Ok,
                Err(status) => {
                    unsafe { crate::memory::free_c_string(ptr) };
                    status
                }
            }
        }
        Err(err) => status_from_error(&err),
    }
}

/// Deliver an infallible unit result for fallible unit commands.
pub(crate) fn deliver_unit(result: Result<(), MarmotKitError>) -> MarmotStatus {
    match result {
        Ok(()) => MarmotStatus::Ok,
        Err(err) => status_from_error(&err),
    }
}

/// Deliver a fallible `Vec<u8>` result as an owned `(ptr, len)` byte
/// buffer. The caller frees it with `marmot_bytes_free`. Empty is
/// `(NULL, 0)`.
pub(crate) unsafe fn deliver_bytes(
    result: Result<Vec<u8>, MarmotKitError>,
    out_data: *mut *mut u8,
    out_len: *mut usize,
) -> MarmotStatus {
    match result {
        Ok(bytes) => {
            if out_data.is_null() || out_len.is_null() {
                crate::status::set_last_error("out-pointer argument was NULL");
                return MarmotStatus::NullPointer;
            }
            let (ptr, len) = crate::memory::owned_vec(bytes);
            unsafe {
                out_data.write(ptr);
                out_len.write(len);
            }
            MarmotStatus::Ok
        }
        Err(err) => status_from_error(&err),
    }
}

/// Generate one `extern "C"` command wrapper from a one-line spec:
///
/// ```text
/// c_cmd! {
///     /// docs (become the C header docs)
///     async fn marmot_create_group(
///         account_ref: str, name: str, member_refs: str_arr, description: opt_str,
///     ) -> string = create_group;
/// }
/// ```
///
/// Arg kinds: `str` (required string), `opt_str` (nullable string),
/// `str_arr` (string array + length pair), `val: T` (scalar by value),
/// `flag` (boolean as `uint8_t` — see [`crate::memory::c_bool`]),
/// `f/f_len: opt_num_arr T` (nullable scalar array + length pair; NULL
/// with length 0 means unset).
/// Return kinds: `unit`, `scalar(T)`, `string`, `bytes`, `rec(Mirror)`,
/// `opt_rec(Mirror)`. `sync`/`async` selects direct call vs `block_on`.
macro_rules! c_cmd {
    ($($(#[$m:meta])* $mode:ident fn $cname:ident($($args:tt)*) -> $rk:ident $(($($rt:tt)+))? = $method:ident;)+) => {
        $(c_cmd!(@munch [$(#[$m])*] $mode, $cname, $method, ($rk $(($($rt)+))?), {} {} {} $($args)*);)+
    };

    // Terminal: all args munched — emit per return kind.
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, (unit), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*}) => {
        $($m)*
        ///
        /// # Safety
        /// `client` must be a live handle; string arguments must be valid
        /// NUL-terminated strings (nullable ones may be NULL); array
        /// arguments must hold their stated length (or be NULL with
        /// length 0); out-pointers must be valid.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $cname(
            client: *const MarmotClient,
            $($p)*
        ) -> MarmotStatus {
            ffi_guard(|| {
                let client = try_arg!(unsafe { client_ref(client) });
                $($r)*
                deliver_unit(c_cmd!(@call client, $mode, $method, $($a)*))
            })
        }
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, (scalar($t:ty)), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*}) => {
        $($m)*
        ///
        /// # Safety
        /// `client` must be a live handle; string arguments must be valid
        /// NUL-terminated strings (nullable ones may be NULL); array
        /// arguments must hold their stated length (or be NULL with
        /// length 0); out-pointers must be valid.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $cname(
            client: *const MarmotClient,
            $($p)*
            out: *mut $t,
        ) -> MarmotStatus {
            ffi_guard(|| {
                try_arg!(unsafe { crate::preflight_out(out) });
                let client = try_arg!(unsafe { client_ref(client) });
                $($r)*
                unsafe { deliver_scalar(c_cmd!(@call client, $mode, $method, $($a)*), out) }
            })
        }
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, (string), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*}) => {
        $($m)*
        ///
        /// # Safety
        /// `client` must be a live handle; string arguments must be valid
        /// NUL-terminated strings (nullable ones may be NULL); array
        /// arguments must hold their stated length (or be NULL with
        /// length 0); out-pointers must be valid.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $cname(
            client: *const MarmotClient,
            $($p)*
            out: *mut *mut c_char,
        ) -> MarmotStatus {
            ffi_guard(|| {
                try_arg!(unsafe { crate::preflight_out_ptr(out) });
                let client = try_arg!(unsafe { client_ref(client) });
                $($r)*
                unsafe { deliver_string(c_cmd!(@call client, $mode, $method, $($a)*), out) }
            })
        }
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, (enum_ret($t:ty)), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*}) => {
        $($m)*
        ///
        /// # Safety
        /// `client` must be a live handle; string arguments must be valid
        /// NUL-terminated strings (nullable ones may be NULL); array
        /// arguments must hold their stated length (or be NULL with
        /// length 0); out-pointers must be valid.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $cname(
            client: *const MarmotClient,
            $($p)*
            out: *mut $t,
        ) -> MarmotStatus {
            ffi_guard(|| {
                try_arg!(unsafe { crate::check_out(out) });
                let client = try_arg!(unsafe { client_ref(client) });
                $($r)*
                unsafe { deliver_enum(c_cmd!(@call client, $mode, $method, $($a)*), out) }
            })
        }
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, (opt_string), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*}) => {
        $($m)*
        ///
        /// # Safety
        /// `client` must be a live handle; string arguments must be valid
        /// NUL-terminated strings (nullable ones may be NULL); array
        /// arguments must hold their stated length (or be NULL with
        /// length 0); out-pointers must be valid.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $cname(
            client: *const MarmotClient,
            $($p)*
            out: *mut *mut c_char,
        ) -> MarmotStatus {
            ffi_guard(|| {
                try_arg!(unsafe { crate::preflight_out_ptr(out) });
                let client = try_arg!(unsafe { client_ref(client) });
                $($r)*
                unsafe { deliver_opt_string(c_cmd!(@call client, $mode, $method, $($a)*), out) }
            })
        }
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, (bytes), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*}) => {
        $($m)*
        ///
        /// # Safety
        /// `client` must be a live handle; string arguments must be valid
        /// NUL-terminated strings (nullable ones may be NULL); array
        /// arguments must hold their stated length (or be NULL with
        /// length 0); out-pointers must be valid.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $cname(
            client: *const MarmotClient,
            $($p)*
            out_data: *mut *mut u8,
            out_len: *mut usize,
        ) -> MarmotStatus {
            ffi_guard(|| {
                try_arg!(unsafe { crate::preflight_out_ptr(out_data) });
                try_arg!(unsafe { crate::preflight_out(out_len) });
                let client = try_arg!(unsafe { client_ref(client) });
                $($r)*
                unsafe { deliver_bytes(c_cmd!(@call client, $mode, $method, $($a)*), out_data, out_len) }
            })
        }
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, (rec($t:ty)), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*}) => {
        $($m)*
        ///
        /// # Safety
        /// `client` must be a live handle; string arguments must be valid
        /// NUL-terminated strings (nullable ones may be NULL); array
        /// arguments must hold their stated length (or be NULL with
        /// length 0); out-pointers must be valid.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $cname(
            client: *const MarmotClient,
            $($p)*
            out: *mut *mut $t,
        ) -> MarmotStatus {
            ffi_guard(|| {
                try_arg!(unsafe { crate::preflight_out_ptr(out) });
                let client = try_arg!(unsafe { client_ref(client) });
                $($r)*
                unsafe { deliver(c_cmd!(@call client, $mode, $method, $($a)*), out) }
            })
        }
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, (opt_rec($t:ty)), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*}) => {
        $($m)*
        ///
        /// # Safety
        /// `client` must be a live handle; string arguments must be valid
        /// NUL-terminated strings (nullable ones may be NULL); array
        /// arguments must hold their stated length (or be NULL with
        /// length 0); out-pointers must be valid.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $cname(
            client: *const MarmotClient,
            $($p)*
            out: *mut *mut $t,
        ) -> MarmotStatus {
            ffi_guard(|| {
                try_arg!(unsafe { crate::preflight_out_ptr(out) });
                let client = try_arg!(unsafe { client_ref(client) });
                $($r)*
                unsafe { deliver_opt(c_cmd!(@call client, $mode, $method, $($a)*), out) }
            })
        }
    };

    // Arg munchers.
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, ($($ret:tt)+), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*} $f:ident: str $(, $($rest:tt)*)?) => {
        c_cmd!(@munch [$($m)*] $mode, $cname, $method, ($($ret)+),
            {$($p)* $f: *const c_char,}
            {$($r)* let $f = try_arg!(unsafe { required_str($f) });}
            {$($a)* $f,}
            $($($rest)*)?);
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, ($($ret:tt)+), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*} $f:ident: opt_str $(, $($rest:tt)*)?) => {
        c_cmd!(@munch [$($m)*] $mode, $cname, $method, ($($ret)+),
            {$($p)* $f: *const c_char,}
            {$($r)* let $f = try_arg!(unsafe { crate::memory::optional_str($f) });}
            {$($a)* $f,}
            $($($rest)*)?);
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, ($($ret:tt)+), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*} $f:ident/$fl:ident: str_arr $(, $($rest:tt)*)?) => {
        c_cmd!(@munch [$($m)*] $mode, $cname, $method, ($($ret)+),
            {$($p)* $f: *const *const c_char, $fl: usize,}
            {$($r)* let $f = try_arg!(unsafe { str_array($f, $fl) });}
            {$($a)* $f,}
            $($($rest)*)?);
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, ($($ret:tt)+), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*} $f:ident: val $t:ty $(, $($rest:tt)*)?) => {
        c_cmd!(@munch [$($m)*] $mode, $cname, $method, ($($ret)+),
            {$($p)* $f: $t,}
            {$($r)*}
            {$($a)* $f,}
            $($($rest)*)?);
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, ($($ret:tt)+), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*} $f:ident/$fl:ident: opt_num_arr $t:ty $(, $($rest:tt)*)?) => {
        c_cmd!(@munch [$($m)*] $mode, $cname, $method, ($($ret)+),
            {$($p)* $f: *const $t, $fl: usize,}
            {$($r)* let $f = try_arg!(unsafe { crate::memory::opt_num_array($f, $fl) });}
            {$($a)* $f,}
            $($($rest)*)?);
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, ($($ret:tt)+), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*} $f:ident: flag $(, $($rest:tt)*)?) => {
        c_cmd!(@munch [$($m)*] $mode, $cname, $method, ($($ret)+),
            {$($p)* $f: u8,}
            {$($r)* let $f = crate::memory::c_bool($f);}
            {$($a)* $f,}
            $($($rest)*)?);
    };
    (@munch [$($m:tt)*] $mode:ident, $cname:ident, $method:ident, ($($ret:tt)+), {$($p:tt)*} {$($r:tt)*} {$($a:tt)*} $hf:ident/$f:ident: opt_val $t:ty $(, $($rest:tt)*)?) => {
        c_cmd!(@munch [$($m)*] $mode, $cname, $method, ($($ret)+),
            {$($p)* $hf: u8, $f: $t,}
            {$($r)* let $f = crate::memory::c_bool($hf).then_some($f);}
            {$($a)* $f,}
            $($($rest)*)?);
    };

    // Call modes.
    (@call $client:ident, sync, $method:ident, $($a:tt)*) => {
        $client.marmot.$method($($a)*)
    };
    (@call $client:ident, async, $method:ident, $($a:tt)*) => {
        $client.block_on($client.marmot.$method($($a)*))
    };
}

c_cmd! {
    /// List every account known to this device. Free the result with
    /// `marmot_account_summary_list_free`.
    sync fn marmot_list_accounts() -> rec(MarmotAccountSummaryList) = list_accounts;

    /// Per-account unread aggregates for the account-switcher badge.
    /// Free with `marmot_account_unread_list_free`.
    sync fn marmot_account_unread_summary() -> rec(MarmotAccountUnreadList) = account_unread_summary;

    /// Remove an account and its local state from this device.
    async fn marmot_remove_account(account_ref: str) -> unit = remove_account;

    /// Destructive sign-out: leave groups, delete relay KeyPackages, wipe
    /// local state. Every stage is reported in the outcome. Free with
    /// `marmot_wipe_outcome_free`.
    async fn marmot_sign_out_and_wipe(account_ref: str) -> rec(MarmotWipeOutcome) = sign_out_and_wipe;

    /// Non-destructive sign-out: deactivate the account on this device,
    /// keeping local state so it can sign back in later. When
    /// `delete_key_packages` is true, relay-published KeyPackages get
    /// NIP-09 deletions. Free with `marmot_sign_out_outcome_free`.
    async fn marmot_sign_out(account_ref: str, delete_key_packages: flag) -> rec(MarmotSignOutOutcome) = sign_out;

    /// Create a brand-new Nostr identity, store its secret in the account
    /// secret store, and publish initial relay lists + key package. Free with
    /// `marmot_account_summary_free`.
    async fn marmot_create_identity(default_relays/default_relays_len: str_arr, bootstrap_relays/bootstrap_relays_len: str_arr) -> rec(MarmotAccountSummary) = create_identity;

    /// Log in with an existing identity: an `nsec` (private key) for a
    /// local-signing account, or an `npub` to track a public identity.
    /// Free with `marmot_account_summary_free`.
    async fn marmot_login(identity: str, default_relays/default_relays_len: str_arr, bootstrap_relays/bootstrap_relays_len: str_arr) -> rec(MarmotAccountSummary) = login;

    /// Re-activate a non-destructively signed-out local account. Free
    /// with `marmot_account_summary_free`.
    async fn marmot_sign_in_account(account_ref: str) -> rec(MarmotAccountSummary) = sign_in_account;

    /// Publish NIP-65 + inbox relay lists for the account. Idempotent.
    async fn marmot_publish_relay_lists(account_ref: str, default_relays/default_relays_len: str_arr, bootstrap_relays/bootstrap_relays_len: str_arr) -> unit = publish_relay_lists;

    /// The account's NIP-65 relay list. Free with
    /// `marmot_string_list_free`.
    sync fn marmot_account_nip65_relays(account_ref: str) -> rec(MarmotStringList) = account_nip65_relays;

    /// The account's inbox relay list. Free with
    /// `marmot_string_list_free`.
    sync fn marmot_account_inbox_relays(account_ref: str) -> rec(MarmotStringList) = account_inbox_relays;

    /// Local + relay-published KeyPackages for the account. Free with
    /// `marmot_account_key_package_list_free`.
    async fn marmot_account_key_packages(account_ref: str, bootstrap_relays/bootstrap_relays_len: str_arr) -> rec(MarmotAccountKeyPackageList) = account_key_packages;

    /// Publish a fresh KeyPackage. Writes the accepting-relay count.
    async fn marmot_publish_new_key_package(account_ref: str) -> scalar(u64) = publish_new_key_package;

    /// Re-publish the latest cached KeyPackage when possible, otherwise
    /// publish a fresh one. Writes the accepting-relay count.
    async fn marmot_republish_key_package(account_ref: str) -> scalar(u64) = republish_key_package;

    /// Rotate the account's KeyPackage: mint and publish a fresh one,
    /// superseding the current slot (the sanctioned repair for an
    /// epoch-stalled group; see `MARMOT_EVENT_EPOCH_STALL_ESCALATED`).
    /// Writes the accepting-relay count. `marmot_publish_new_key_package`
    /// is the same operation under its legacy name.
    async fn marmot_rotate_key_package(account_ref: str) -> scalar(u64) = rotate_key_package;

    /// Publish a NIP-09 deletion for a KeyPackage event. Writes the
    /// accepting-relay count.
    async fn marmot_delete_account_key_package(account_ref: str, event_id_hex: str, relays/relays_len: str_arr) -> scalar(u64) = delete_account_key_package;

    /// Replace the account's NIP-65 relay list and publish it. Free with
    /// `marmot_account_relay_lists_free`.
    async fn marmot_set_account_nip65_relays(account_ref: str, relays/relays_len: str_arr, bootstrap_relays/bootstrap_relays_len: str_arr) -> rec(MarmotAccountRelayLists) = set_account_nip65_relays;

    /// Replace the account's inbox relay list and publish it. Free with
    /// `marmot_account_relay_lists_free`.
    async fn marmot_set_account_inbox_relays(account_ref: str, relays/relays_len: str_arr, bootstrap_relays/bootstrap_relays_len: str_arr) -> rec(MarmotAccountRelayLists) = set_account_inbox_relays;

    /// Export the account's raw private key as `nsec1…` bech32.
    /// SENSITIVE: the reveal is audit-logged and permanently marks the
    /// account's key-security byte as handled-insecurely. Free the string
    /// with `marmot_string_free` as soon as it has been displayed.
    sync fn marmot_reveal_nsec(account_ref: str) -> string = reveal_nsec;

    /// Export the account's private key NIP-49-encrypted under
    /// `passphrase`. Free with `marmot_string_free`.
    sync fn marmot_export_encrypted_secret_key(account_ref: str, passphrase: str) -> string = export_encrypted_secret_key;

    /// Create a new MLS group with `name` and the given members
    /// (referenced by `npub` or hex account id). Writes the new group id
    /// as a hex string; free it with `marmot_string_free`.
    async fn marmot_create_group(account_ref: str, name: str, member_refs/member_refs_len: str_arr, description: opt_str) -> string = create_group;

    /// Normalize a member reference (hex, `npub`, `nostr:npub...`,
    /// `marmot://profile/...`). Free with `marmot_member_ref_free`.
    sync fn marmot_normalize_member_ref(member_ref: str) -> rec(MarmotMemberRef) = normalize_member_ref;

    /// Membership roster for `group_id_hex`. Free with
    /// `marmot_app_group_member_record_list_free`.
    async fn marmot_group_members(account_ref: str, group_id_hex: str) -> rec(MarmotAppGroupMemberRecordList) = group_members;

    /// Group plus enriched member rows for detail screens. Free with
    /// `marmot_group_details_free`.
    async fn marmot_group_details(account_ref: str, group_id_hex: str) -> rec(MarmotGroupDetails) = group_details;

    /// Current caller permissions plus per-member action availability.
    /// Free with `marmot_group_management_state_free`.
    async fn marmot_group_management_state(account_ref: str, group_id_hex: str) -> rec(MarmotGroupManagementState) = group_management_state;

    /// Invite members (by `npub` or hex account id) into the group.
    /// Requires admin. Free with `marmot_send_summary_free`.
    async fn marmot_invite_members(account_ref: str, group_id_hex: str, member_refs/member_refs_len: str_arr) -> rec(MarmotSendSummary) = invite_members;

    /// Remove members from the group. Requires admin; preflight rejects
    /// self-removal and removing the last admin. Free with
    /// `marmot_send_summary_free`.
    async fn marmot_remove_members(account_ref: str, group_id_hex: str, member_refs/member_refs_len: str_arr) -> rec(MarmotSendSummary) = remove_members;

    /// Leave the group as the active account. Admins must self-demote
    /// first. Free with `marmot_send_summary_free`.
    async fn marmot_leave_group(account_ref: str, group_id_hex: str) -> rec(MarmotSendSummary) = leave_group;

    /// Delete this group's local app data without an MLS leave. Cancel
    /// active UI subscriptions for the group first. MLS state stays
    /// intact; a future fresh delivery can recreate a chat row. Writes
    /// true if any local rows or a live route were removed.
    async fn marmot_delete_group_local(account_ref: str, group_id_hex: str) -> scalar(bool) = delete_group_local;

    /// Set the per-group disappearing-message retention.
    /// `disappearing_message_secs` of `0` disables expiry. Free with
    /// `marmot_send_summary_free`.
    async fn marmot_update_message_retention(account_ref: str, group_id_hex: str, disappearing_message_secs: val u64) -> rec(MarmotSendSummary) = update_message_retention;

    /// Accept a pending group invite; writes the now-confirmed group
    /// record. Free with `marmot_app_group_record_free`.
    async fn marmot_accept_group_invite(account_ref: str, group_id_hex: str) -> rec(MarmotAppGroupRecord) = accept_group_invite;

    /// Decline a pending group invite; writes the updated group record
    /// plus the decline publish summary. Free with
    /// `marmot_group_invite_decline_result_free`.
    async fn marmot_decline_group_invite(account_ref: str, group_id_hex: str) -> rec(MarmotGroupInviteDeclineResult) = decline_group_invite;

    /// Update the group's name and/or description. NULL leaves a field
    /// unchanged. Free with `marmot_send_summary_free`.
    async fn marmot_update_group_profile(account_ref: str, group_id_hex: str, name: opt_str, description: opt_str) -> rec(MarmotSendSummary) = update_group_profile;

    /// Set (or clear, with `url` NULL) the group's URL-based avatar. The
    /// URL is validated (https-only, no localhost/private hosts) and
    /// normalized before commit. Free with `marmot_send_summary_free`.
    async fn marmot_update_group_avatar_url(account_ref: str, group_id_hex: str, url: opt_str, dim: opt_str, thumbhash: opt_str) -> rec(MarmotSendSummary) = update_group_avatar_url;

    /// Fetch, verify, and decrypt the group's Blossom-hosted encrypted
    /// image. Needs a relay/Blossom, so it fails offline. Free the buffer
    /// with `marmot_bytes_free`.
    async fn marmot_download_group_blossom_image(account_ref: str, group_id_hex: str) -> bytes = download_group_blossom_image;

    /// Grant admin rights to `member_ref` (npub or hex). Requires admin.
    /// Free with `marmot_send_summary_free`.
    async fn marmot_promote_admin(account_ref: str, group_id_hex: str, member_ref: str) -> rec(MarmotSendSummary) = promote_admin;

    /// Revoke `member_ref`'s admin rights. Free with
    /// `marmot_send_summary_free`.
    async fn marmot_demote_admin(account_ref: str, group_id_hex: str, member_ref: str) -> rec(MarmotSendSummary) = demote_admin;

    /// Step down as an admin (demote the active account). Free with
    /// `marmot_send_summary_free`.
    async fn marmot_self_demote_admin(account_ref: str, group_id_hex: str) -> rec(MarmotSendSummary) = self_demote_admin;

    /// `marmot_invite_members` plus refreshed details and management
    /// state in one round trip. Free with
    /// `marmot_group_mutation_result_free`.
    async fn marmot_invite_members_detailed(account_ref: str, group_id_hex: str, member_refs/member_refs_len: str_arr) -> rec(MarmotGroupMutationResult) = invite_members_detailed;

    /// `marmot_remove_members` plus refreshed details and management
    /// state. Free with `marmot_group_mutation_result_free`.
    async fn marmot_remove_members_detailed(account_ref: str, group_id_hex: str, member_refs/member_refs_len: str_arr) -> rec(MarmotGroupMutationResult) = remove_members_detailed;

    /// `marmot_promote_admin` plus refreshed details and management
    /// state. Free with `marmot_group_mutation_result_free`.
    async fn marmot_promote_admin_detailed(account_ref: str, group_id_hex: str, member_ref: str) -> rec(MarmotGroupMutationResult) = promote_admin_detailed;

    /// `marmot_demote_admin` plus refreshed details and management state.
    /// Free with `marmot_group_mutation_result_free`.
    async fn marmot_demote_admin_detailed(account_ref: str, group_id_hex: str, member_ref: str) -> rec(MarmotGroupMutationResult) = demote_admin_detailed;

    /// `marmot_self_demote_admin` plus refreshed details and management
    /// state. Free with `marmot_group_mutation_result_free`.
    async fn marmot_self_demote_admin_detailed(account_ref: str, group_id_hex: str) -> rec(MarmotGroupMutationResult) = self_demote_admin_detailed;

    /// Current MLS state (epoch, member count, required components) for
    /// the conversation developer/debug view. Free with
    /// `marmot_app_group_mls_state_free`.
    async fn marmot_group_mls_state(account_ref: str, group_id_hex: str) -> rec(MarmotAppGroupMlsState) = group_mls_state;

    /// Stored groups that failed session-open hydration and were skipped.
    /// Surface them in a per-group recovery flow and offer
    /// `marmot_retry_hydrate_quarantined_group`. Free with
    /// `marmot_app_quarantined_group_list_free`.
    async fn marmot_quarantined_groups(account_ref: str) -> rec(MarmotAppQuarantinedGroupList) = quarantined_groups;

    /// Re-attempt hydration of a single quarantined group. Writes true if
    /// the group recovered and is now a live chat, false if it stays
    /// quarantined. Unknown-group status if the id is not quarantined.
    async fn marmot_retry_hydrate_quarantined_group(account_ref: str, group_id_hex: str) -> scalar(bool) = retry_hydrate_quarantined_group;

    /// Interrupt retry backoff for durable outbound work after the host has
    /// observed usable connectivity.
    async fn marmot_notify_connectivity_restored() -> unit = notify_connectivity_restored;

    /// Flag a group archived (or restore it). Local-only projection
    /// state. Free with `marmot_app_group_record_free`.
    async fn marmot_set_group_archived(account_ref: str, group_id_hex: str, archived: flag) -> rec(MarmotAppGroupRecord) = set_group_archived;

    /// Send a chat text message to the group. Free with
    /// `marmot_send_summary_free`.
    async fn marmot_send_text(account_ref: str, group_id_hex: str, text: str) -> rec(MarmotSendSummary) = send_text;

    /// Re-drive delivery/convergence for the group (e.g. a stuck pending
    /// own message) without minting duplicates. Free with
    /// `marmot_send_summary_free`.
    async fn marmot_retry_group_convergence(account_ref: str, group_id_hex: str) -> rec(MarmotSendSummary) = retry_group_convergence;

    /// React to a message with `emoji`. Free with
    /// `marmot_send_summary_free`.
    async fn marmot_react_to_message(account_ref: str, group_id_hex: str, target_message_id: str, emoji: str) -> rec(MarmotSendSummary) = react_to_message;

    /// Remove this account's reaction from a message. Free with
    /// `marmot_send_summary_free`.
    async fn marmot_unreact_from_message(account_ref: str, group_id_hex: str, target_message_id: str) -> rec(MarmotSendSummary) = unreact_from_message;

    /// Reply to a message. Free with `marmot_send_summary_free`.
    async fn marmot_reply_to_message(account_ref: str, group_id_hex: str, target_message_id: str, text: str) -> rec(MarmotSendSummary) = reply_to_message;

    /// Request deletion of an own message. Free with
    /// `marmot_send_summary_free`.
    async fn marmot_delete_message(account_ref: str, group_id_hex: str, target_message_id: str) -> rec(MarmotSendSummary) = delete_message;

    /// Edit an own message's content. Free with
    /// `marmot_send_summary_free`.
    async fn marmot_edit_message(account_ref: str, group_id_hex: str, target_message_id: str, content: str) -> rec(MarmotSendSummary) = edit_message;

    /// Securely delete this group's expired disappearing messages now.
    /// Free with `marmot_secure_delete_expired_result_free`.
    async fn marmot_secure_delete_expired(account_ref: str, group_id_hex: str) -> rec(MarmotSecureDeleteExpiredResult) = secure_delete_expired;

    /// One-time catch-up across every running account (e.g. after a push
    /// wake).
    async fn marmot_catch_up_accounts() -> unit = catch_up_accounts;

    /// Per-account notification switches. Free with
    /// `marmot_notification_settings_free`.
    sync fn marmot_notification_settings(account_ref: str) -> rec(MarmotNotificationSettings) = notification_settings;

    /// Toggle local notifications for the account. Free with
    /// `marmot_notification_settings_free`.
    sync fn marmot_set_local_notifications_enabled(account_ref: str, enabled: flag) -> rec(MarmotNotificationSettings) = set_local_notifications_enabled;

    /// Toggle native push for the account. Free with
    /// `marmot_notification_settings_free`.
    async fn marmot_set_native_push_enabled(account_ref: str, enabled: flag) -> rec(MarmotNotificationSettings) = set_native_push_enabled;

    /// The account's current push registration; writes NULL with
    /// `MARMOT_STATUS_OK` when there is none. Free with
    /// `marmot_push_registration_free`.
    sync fn marmot_push_registration(account_ref: str) -> opt_rec(MarmotPushRegistration) = push_registration;

    /// Remove the account's push registration and share the removal.
    /// Free with `marmot_push_registration_share_outcome_free`.
    async fn marmot_clear_push_registration(account_ref: str) -> rec(MarmotPushRegistrationShareOutcome) = clear_push_registration;

    /// Per-group push token debug info. Free with
    /// `marmot_group_push_debug_info_free`.
    async fn marmot_group_push_debug_info(account_ref: str, group_id_hex: str) -> rec(MarmotGroupPushDebugInfo) = group_push_debug_info;

    /// The account's full relay-list state. Free with
    /// `marmot_account_relay_lists_free`.
    sync fn marmot_account_relay_lists(account_ref: str) -> rec(MarmotAccountRelayLists) = account_relay_lists;

    /// Current relay-telemetry export settings. Free with
    /// `marmot_relay_telemetry_settings_free`.
    sync fn marmot_relay_telemetry_settings() -> rec(MarmotRelayTelemetrySettings) = relay_telemetry_settings;

    /// Stable anonymous install id for telemetry. Free with
    /// `marmot_string_free`.
    sync fn marmot_telemetry_install_id() -> string = telemetry_install_id;

    /// Current audit-log recorder settings. Free with
    /// `marmot_audit_log_settings_free`.
    sync fn marmot_audit_log_settings() -> rec(MarmotAuditLogSettings) = audit_log_settings;

    /// On-disk audit-log files. Free with
    /// `marmot_audit_log_file_list_free`.
    sync fn marmot_audit_log_files() -> rec(MarmotAuditLogFileList) = audit_log_files;

    /// Upload one audit-log file to `endpoint`. Free with
    /// `marmot_audit_log_upload_result_free`.
    async fn marmot_post_audit_log_file(path: str, endpoint: str) -> rec(MarmotAuditLogUploadResult) = post_audit_log_file;

    /// Delete one on-disk audit-log file. Free with
    /// `marmot_audit_log_delete_result_free`.
    async fn marmot_delete_audit_log_file(path: str) -> rec(MarmotAuditLogDeleteResult) = delete_audit_log_file;

    /// Run one tracker-driven upload pass with the configured tracker.
    /// Free with `marmot_audit_log_tracker_update_result_free`.
    async fn marmot_post_audit_log_tracker_update() -> rec(MarmotAuditLogTrackerUpdateResult) = post_audit_log_tracker_update;

    /// The account's chat list rows. Free with
    /// `marmot_chat_list_row_list_free`.
    sync fn marmot_chat_list(account_ref: str, include_archived: flag) -> rec(MarmotChatListRowList) = chat_list;

    /// Initialize read state for a conversation being opened; writes the
    /// refreshed row, or NULL with `MARMOT_STATUS_OK` when the group has
    /// no row. Free with `marmot_chat_list_row_free`.
    sync fn marmot_initialize_chat_read_state(account_ref: str, group_id_hex: str) -> opt_rec(MarmotChatListRow) = initialize_chat_read_state;

    /// Mark a timeline message read; writes the refreshed row, or NULL
    /// with `MARMOT_STATUS_OK`. Free with `marmot_chat_list_row_free`.
    sync fn marmot_mark_timeline_message_read(account_ref: str, group_id_hex: str, message_id_hex: str) -> opt_rec(MarmotChatListRow) = mark_timeline_message_read;

    /// Mark a conversation manually unread (or clear that mark); writes
    /// the refreshed row, or NULL with `MARMOT_STATUS_OK` when the group
    /// has no row. Free with `marmot_chat_list_row_free`.
    sync fn marmot_set_chat_manually_unread(account_ref: str, group_id_hex: str, manually_unread: flag) -> opt_rec(MarmotChatListRow) = set_chat_manually_unread;

    /// Pin or unpin a conversation. Writes the account's full pin state.
    /// Free with `marmot_chat_pin_state_free`.
    sync fn marmot_set_chat_pinned(account_ref: str, group_id_hex: str, pinned: flag) -> rec(MarmotChatPinState) = set_chat_pinned;

    /// Replace the pinned-section order. `ordered_group_ids` lists every
    /// pinned group in display order. Free with
    /// `marmot_chat_pin_state_free`.
    sync fn marmot_set_pinned_chat_order(account_ref: str, ordered_group_ids/ordered_group_ids_len: str_arr) -> rec(MarmotChatPinState) = set_pinned_chat_order;

    /// The conversation's local mute state. Free with
    /// `marmot_chat_notification_settings_free`.
    sync fn marmot_chat_notification_settings(account_ref: str, group_id_hex: str) -> rec(MarmotChatNotificationSettings) = chat_notification_settings;

    /// Mute a conversation. `has_muted_until_ms` plus `muted_until_ms`
    /// set a timed mute; leaving the flag unset mutes indefinitely. Free
    /// with `marmot_chat_notification_settings_free`.
    sync fn marmot_set_chat_muted(account_ref: str, group_id_hex: str, has_muted_until_ms/muted_until_ms: opt_val i64) -> rec(MarmotChatNotificationSettings) = set_chat_muted;

    /// Unmute a conversation. Free with
    /// `marmot_chat_notification_settings_free`.
    sync fn marmot_clear_chat_muted(account_ref: str, group_id_hex: str) -> rec(MarmotChatNotificationSettings) = clear_chat_muted;

    /// Stored raw app messages for a group (`group_id_hex` non-NULL) or
    /// the whole account (NULL), newest-last, capped by `limit` when
    /// `has_limit`. `kinds` restricts the result to those Nostr event
    /// kinds; pass NULL with length 0 for every kind. Free with
    /// `marmot_app_message_record_list_free`.
    sync fn marmot_messages(account_ref: str, group_id_hex: opt_str, has_limit/limit: opt_val u32, kinds/kinds_len: opt_num_arr u64) -> rec(MarmotAppMessageRecordList) = messages;

    /// Stored media records for the group, capped by `limit` when
    /// `has_limit`. Free with `marmot_media_record_list_free`.
    sync fn marmot_list_media(account_ref: str, group_id_hex: str, has_limit/limit: opt_val u32) -> rec(MarmotMediaRecordList) = list_media;

    /// Cached kind-0 profile for an account id; writes NULL with
    /// `MARMOT_STATUS_OK` when unknown. Free with
    /// `marmot_user_profile_metadata_free`.
    sync fn marmot_user_profile(account_id_hex: str) -> opt_rec(MarmotUserProfileMetadata) = user_profile;

    /// Refresh the cached profile for an account id from `relays`.
    async fn marmot_refresh_profile(account_id_hex: str, relays/relays_len: str_arr) -> unit = refresh_profile;

    /// The account ids this account follows (NIP-02). Free with
    /// `marmot_string_list_free`.
    sync fn marmot_account_follows(account_ref: str) -> rec(MarmotStringList) = account_follows;

    /// Whether `user_ref` (`npub` or hex account id) is followed.
    sync fn marmot_is_following(account_ref: str, user_ref: str) -> scalar(bool) = is_following;

    /// Follow `user_ref` and publish the updated list. Writes the new
    /// follow set. Free with `marmot_string_list_free`.
    async fn marmot_follow_user(account_ref: str, user_ref: str) -> rec(MarmotStringList) = follow_user;

    /// Unfollow `user_ref` and publish the updated list. Free with
    /// `marmot_string_list_free`.
    async fn marmot_unfollow_user(account_ref: str, user_ref: str) -> rec(MarmotStringList) = unfollow_user;

    /// Discard the local state of an account whose setup never completed.
    /// `acknowledge_possible_key_package_orphan` confirms the caller
    /// accepts that a published KeyPackage may be left orphaned.
    async fn marmot_reset_incomplete_account_setup(nsec: str, acknowledge_possible_key_package_orphan: flag) -> unit = reset_incomplete_account_setup;

    /// Sign in and finish a setup that was interrupted partway. Free with
    /// `marmot_account_summary_free`.
    async fn marmot_login_recovering_incomplete_setup(nsec: str, default_relays/default_relays_len: str_arr, bootstrap_relays/bootstrap_relays_len: str_arr, acknowledge_possible_key_package_orphan: flag) -> rec(MarmotAccountSummary) = login_recovering_incomplete_setup;

    /// Fetch a profile image by URL, refusing anything over `max_bytes`.
    /// Free the buffer with `marmot_bytes_free`.
    async fn marmot_download_profile_image(url: str, max_bytes: val u64) -> bytes = download_profile_image;

    /// The durable chat-list row for one group; writes NULL with
    /// `MARMOT_STATUS_OK` when the group has no row. Free with
    /// `marmot_chat_list_row_free`.
    sync fn marmot_chat_list_row(account_ref: str, group_id_hex: str) -> opt_rec(MarmotChatListRow) = chat_list_row;

    /// The `website` field of a cached kind-0 profile; writes NULL with
    /// `MARMOT_STATUS_OK` when unknown. Free with `marmot_string_free`.
    sync fn marmot_user_profile_website(account_id_hex: str) -> opt_string = user_profile_website;

    /// Discard the stored draft for a conversation. Absent is not an
    /// error.
    sync fn marmot_delete_message_draft(account_ref: str, group_id_hex: str) -> unit = delete_message_draft;

    /// Clear the group's encrypted Blossom avatar by committing the
    /// absent image component. Requires admin. Free with
    /// `marmot_send_summary_free`.
    async fn marmot_clear_group_image(account_ref: str, group_id_hex: str) -> rec(MarmotSendSummary) = clear_group_image;

    /// Opt the group into disbanding, so a later `marmot_disband_group`
    /// is accepted. Requires admin. Free with
    /// `marmot_group_mutation_result_free`.
    async fn marmot_enable_group_disbanding(account_ref: str, group_id_hex: str) -> rec(MarmotGroupMutationResult) = enable_group_disbanding;

    /// Request terminal disbanding of the group. Writes this account's
    /// durable request outcome; free it with
    /// `marmot_disband_request_free`.
    async fn marmot_disband_group(account_ref: str, group_id_hex: str) -> rec(MarmotDisbandRequest) = disband_group;

    /// Acknowledge a failed disband request so the UI can stop surfacing
    /// it. Writes whether a request was actually cleared.
    async fn marmot_acknowledge_disband_failure(account_ref: str, group_id_hex: str) -> scalar(bool) = acknowledge_disband_failure;

    /// `marmot_invite_members` where some invitees join as admins. Free
    /// with `marmot_send_summary_free`.
    async fn marmot_invite_members_with_initial_admins(account_ref: str, group_id_hex: str, member_refs/member_refs_len: str_arr, initial_admin_refs/initial_admin_refs_len: str_arr) -> rec(MarmotSendSummary) = invite_members_with_initial_admins;

    /// `marmot_invite_members_with_initial_admins` plus refreshed details
    /// and management state in one round trip. Free with
    /// `marmot_group_mutation_result_free`.
    async fn marmot_invite_members_detailed_with_initial_admins(account_ref: str, group_id_hex: str, member_refs/member_refs_len: str_arr, initial_admin_refs/initial_admin_refs_len: str_arr) -> rec(MarmotGroupMutationResult) = invite_members_detailed_with_initial_admins;

    /// Queue an MLS self-update commit for the group. Writes the
    /// scheduled job id; free it with `marmot_string_free`.
    async fn marmot_schedule_group_self_update(account_ref: str, group_id_hex: str) -> string = schedule_group_self_update;

    /// Pause the account's periodic maintenance loop.
    async fn marmot_pause_maintenance(account_ref: str) -> unit = pause_maintenance;

    /// Resume the account's periodic maintenance loop.
    async fn marmot_resume_maintenance(account_ref: str) -> unit = resume_maintenance;

    /// Shut the runtime down and release every local file lock, so a
    /// host can suspend without leaving the database leased. The client
    /// handle stays valid but the runtime is finished.
    async fn marmot_client_shutdown_and_close() -> unit = shutdown_and_close;

    /// How far the account's setup has progressed.
    sync fn marmot_account_setup_readiness(account_ref: str) -> enum_ret(MarmotAccountSetupReadiness) = account_setup_readiness;

    /// Create a fresh identity and publish a default profile in one
    /// step. Free with `marmot_identity_creation_result_free`.
    async fn marmot_create_identity_with_profile(default_relays/default_relays_len: str_arr, bootstrap_relays/bootstrap_relays_len: str_arr) -> rec(MarmotIdentityCreationResult) = create_identity_with_profile;

    /// The existing one-to-one conversation with `peer_account_id`, or
    /// NULL with `MARMOT_STATUS_OK` when there is none. Check `reusable`
    /// before opening it. Free with
    /// `marmot_existing_direct_conversation_free`.
    async fn marmot_existing_direct_conversation(account_ref: str, peer_account_id: str) -> opt_rec(MarmotExistingDirectConversation) = existing_direct_conversation;

    /// What the local directory cache holds for each requested id, one
    /// row per request in order. Free with
    /// `marmot_cached_identity_projection_list_free`.
    sync fn marmot_cached_identity_projections(account_id_hexes/account_id_hexes_len: str_arr) -> rec(MarmotCachedIdentityProjectionList) = cached_identity_projections;

    /// Every stored draft for the account, attachment metadata only.
    /// Free with `marmot_message_draft_summary_list_free`.
    sync fn marmot_message_drafts(account_ref: str) -> rec(MarmotMessageDraftSummaryList) = message_drafts;

    /// The stored draft for one conversation, with attachment bytes;
    /// writes NULL with `MARMOT_STATUS_OK` when there is none. Free with
    /// `marmot_message_draft_free`.
    sync fn marmot_message_draft(account_ref: str, group_id_hex: str) -> opt_rec(MarmotMessageDraft) = message_draft;

    /// Resolve and cache KeyPackages for prospective members ahead of a
    /// group creation, so the create itself does not wait on the
    /// network. Free with
    /// `marmot_member_key_package_prewarm_summary_free`.
    async fn marmot_prewarm_group_member_key_packages(account_ref: str, member_refs/member_refs_len: str_arr) -> rec(MarmotMemberKeyPackagePrewarmSummary) = prewarm_group_member_key_packages;

    /// `marmot_create_group` plus the new chat-list row in one round
    /// trip. Free with `marmot_created_group_free`.
    async fn marmot_create_group_detailed(account_ref: str, name: str, member_refs/member_refs_len: str_arr, description: opt_str) -> rec(MarmotCreatedGroup) = create_group_detailed;

    /// Member and admin ids for several groups in one read. Free with
    /// `marmot_app_group_member_ids_list_free`.
    async fn marmot_group_member_ids_page(account_ref: str, group_ids_hex/group_ids_hex_len: str_arr) -> rec(MarmotAppGroupMemberIdsList) = group_member_ids_page;

    /// Group details and management state in one read. Free with
    /// `marmot_group_conversation_snapshot_free`.
    async fn marmot_group_conversation_snapshot(account_ref: str, group_id_hex: str) -> rec(MarmotGroupConversationSnapshot) = group_conversation_snapshot;

    /// The group's member roster at the current MLS epoch. Free with
    /// `marmot_group_roster_free`.
    async fn marmot_group_roster(account_ref: str, group_id_hex: str) -> rec(MarmotGroupRoster) = group_roster;

    /// Upload a staged group image now, so a later group creation can
    /// consume it without waiting. Free with
    /// `marmot_prepared_group_image_upload_free`.
    async fn marmot_upload_prepared_group_image(account_ref: str, upload_id: str) -> rec(MarmotPreparedGroupImageUpload) = upload_prepared_group_image;

    /// Where one staged group image sits in its upload lifecycle. Free
    /// with `marmot_prepared_group_image_upload_free`.
    async fn marmot_prepared_group_image_status(account_ref: str, upload_id: str) -> rec(MarmotPreparedGroupImageUpload) = prepared_group_image_status;

    /// Every staged group image for the account. Free with
    /// `marmot_prepared_group_image_upload_list_free`.
    async fn marmot_prepared_group_images(account_ref: str) -> rec(MarmotPreparedGroupImageUploadList) = prepared_group_images;

    /// Create a group whose avatar is an already-staged prepared image.
    /// Writes the new group id as a hex string; free it with
    /// `marmot_string_free`.
    async fn marmot_create_group_with_prepared_initial_image(account_ref: str, name: str, member_refs/member_refs_len: str_arr, description: opt_str, upload_id: str) -> string = create_group_with_prepared_initial_image;

    /// One group's maintenance state. Free with
    /// `marmot_group_maintenance_status_free`.
    async fn marmot_group_maintenance_status(account_ref: str, group_id_hex: str) -> rec(MarmotGroupMaintenanceStatus) = group_maintenance_status;

    /// The account's KeyPackage slot state; writes NULL with
    /// `MARMOT_STATUS_OK` when no slot exists yet. Free with
    /// `marmot_key_package_maintenance_status_free`.
    async fn marmot_key_package_maintenance_status(account_ref: str) -> opt_rec(MarmotKeyPackageMaintenanceStatus) = key_package_maintenance_status;

    /// Run every maintenance obligation that is due now. Free with
    /// `marmot_maintenance_run_summary_free`.
    async fn marmot_run_due_maintenance(account_ref: str) -> rec(MarmotMaintenanceRunSummary) = run_due_maintenance;

    /// Whether new groups enroll in periodic maintenance.
    async fn marmot_periodic_maintenance_policy(account_ref: str) -> enum_ret(MarmotPeriodicMaintenancePolicy) = periodic_maintenance_policy;

    /// Prune messages past their disappearing-message retention.
    /// `now_ms` is the caller's wall clock. Free with
    /// `marmot_retention_sweep_report_free`.
    async fn marmot_sweep_expired_retention(account_ref: str, now_ms: val u64) -> rec(MarmotRetentionSweepReport) = sweep_expired_retention;
}

/// Parse Markdown text into the display token tree. Infallible: malformed
/// input degrades inside the parser. Free with
/// `marmot_markdown_document_free`.
///
/// # Safety
/// `client` must be a live handle; `text` a valid string; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_parse_markdown(
    client: *const MarmotClient,
    text: *const c_char,
    out: *mut *mut MarmotMarkdownDocument,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let text = try_arg!(unsafe { required_str(text) });
        unsafe {
            deliver(
                Ok::<_, MarmotKitError>(client.marmot.parse_markdown(text)),
                out,
            )
        }
    })
}

/// Best-effort display name for an account id from the local directory
/// cache; writes NULL with `MARMOT_STATUS_OK` when unknown. Free with
/// `marmot_string_free`.
///
/// # Safety
/// `client` must be a live handle; `account_id_hex` a valid string;
/// `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_display_name(
    client: *const MarmotClient,
    account_id_hex: *const c_char,
    out: *mut *mut c_char,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_id_hex = try_arg!(unsafe { required_str(account_id_hex) });
        deliver_plain_opt_string(client.marmot.display_name(account_id_hex), out)
    })
}

/// `npub` encoding of a hex account id; NULL with `MARMOT_STATUS_OK` when
/// the input does not decode. Free with `marmot_string_free`.
///
/// # Safety
/// Same as `marmot_display_name`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_npub(
    client: *const MarmotClient,
    account_id_hex: *const c_char,
    out: *mut *mut c_char,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_id_hex = try_arg!(unsafe { required_str(account_id_hex) });
        deliver_plain_opt_string(client.marmot.npub(account_id_hex), out)
    })
}

/// Hex account id for an `npub`/hex reference; NULL with
/// `MARMOT_STATUS_OK` when the input does not decode. Free with
/// `marmot_string_free`.
///
/// # Safety
/// `client` must be a live handle; `reference` a valid string; `out`
/// valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_account_id_hex(
    client: *const MarmotClient,
    reference: *const c_char,
    out: *mut *mut c_char,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let reference = try_arg!(unsafe { required_str(reference) });
        deliver_plain_opt_string(client.marmot.account_id_hex(reference), out)
    })
}

fn deliver_plain_opt_string(value: Option<String>, out: *mut *mut c_char) -> MarmotStatus {
    let ptr = crate::memory::owned_opt_c_string(value);
    match unsafe { write_out(out, ptr) } {
        Ok(()) => MarmotStatus::Ok,
        Err(status) => {
            unsafe { crate::memory::free_c_string(ptr) };
            status
        }
    }
}

/// Aggregate relay-pool health. Free with `marmot_relay_health_free`.
///
/// # Safety
/// `client` must be a live handle; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_relay_health(
    client: *const MarmotClient,
    out: *mut *mut MarmotRelayHealth,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let health = client.block_on(client.marmot.relay_health());
        unsafe { deliver(Ok::<_, MarmotKitError>(health), out) }
    })
}

/// Replace the relay-telemetry export settings. Free the result with
/// `marmot_relay_telemetry_settings_free`.
///
/// # Safety
/// `client` must be a live handle; `settings` a valid borrowed struct
/// (never freed by the library); `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_set_relay_telemetry_settings(
    client: *const MarmotClient,
    settings: *const MarmotRelayTelemetrySettings,
    out: *mut *mut MarmotRelayTelemetrySettings,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let settings = try_arg!(unsafe { borrowed(settings) });
        unsafe {
            deliver(
                client.block_on(
                    client
                        .marmot
                        .set_relay_telemetry_settings(settings.to_ffi()),
                ),
                out,
            )
        }
    })
}

/// Set the runtime OTLP route for relay telemetry.
///
/// # Safety
/// `client` must be a live handle; `config` a valid borrowed struct.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_set_relay_telemetry_runtime_config(
    client: *const MarmotClient,
    config: *const MarmotRelayTelemetryRuntimeConfig,
) -> MarmotStatus {
    ffi_guard(|| {
        let client = try_arg!(unsafe { client_ref(client) });
        let config = try_arg!(unsafe { borrowed(config) });
        let config = try_arg!(unsafe { config.to_ffi() });
        deliver_unit(client.block_on(client.marmot.set_relay_telemetry_runtime_config(config)))
    })
}

/// Replace the audit-log recorder settings. Free the result with
/// `marmot_audit_log_settings_free`.
///
/// # Safety
/// `client` must be a live handle; `settings` a valid borrowed struct;
/// `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_set_audit_log_settings(
    client: *const MarmotClient,
    settings: *const MarmotAuditLogSettings,
    out: *mut *mut MarmotAuditLogSettings,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let settings = try_arg!(unsafe { borrowed(settings) });
        let settings = settings.to_ffi();
        unsafe {
            deliver(
                client.block_on(client.marmot.set_audit_log_settings(settings)),
                out,
            )
        }
    })
}

/// Replace the audit-log tracker endpoint config. Free the result with
/// `marmot_audit_log_tracker_config_free`.
///
/// # Safety
/// `client` must be a live handle; `config` a valid borrowed struct;
/// `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_set_audit_log_tracker_config(
    client: *const MarmotClient,
    config: *const MarmotAuditLogTrackerConfig,
    out: *mut *mut MarmotAuditLogTrackerConfig,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let config = try_arg!(unsafe { borrowed(config) });
        let config = try_arg!(unsafe { config.to_ffi() });
        unsafe { deliver(client.marmot.set_audit_log_tracker_config(config), out) }
    })
}

/// Publish the account's kind:0 profile metadata. The returned profile is
/// what was actually published. Free with
/// `marmot_user_profile_metadata_free`.
///
/// # Safety
/// `client` must be a live handle; `account_ref` a valid string;
/// `profile` a valid borrowed struct (never freed by the library); relay
/// arrays must hold `len` valid strings (or be NULL with len 0); `out`
/// valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_publish_user_profile(
    client: *const MarmotClient,
    account_ref: *const c_char,
    profile: *const MarmotUserProfileMetadata,
    default_relays: *const *const c_char,
    default_relays_len: usize,
    bootstrap_relays: *const *const c_char,
    bootstrap_relays_len: usize,
    out: *mut *mut MarmotUserProfileMetadata,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let profile = try_arg!(unsafe { borrowed(profile) });
        let profile = try_arg!(unsafe { profile.to_ffi() });
        let default_relays = try_arg!(unsafe { str_array(default_relays, default_relays_len) });
        let bootstrap_relays =
            try_arg!(unsafe { str_array(bootstrap_relays, bootstrap_relays_len) });
        unsafe {
            deliver(
                client.block_on(client.marmot.publish_user_profile(
                    account_ref,
                    profile,
                    default_relays,
                    bootstrap_relays,
                )),
                out,
            )
        }
    })
}

/// Replace the group's encrypted-media default blob endpoints as a full
/// component update. Requires admin. Free with
/// `marmot_send_summary_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid; `endpoints` must point
/// to `endpoints_len` valid caller-owned structs (or be NULL with len 0)
/// — never freed or retained; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_replace_encrypted_media_blob_endpoints(
    client: *const MarmotClient,
    account_ref: *const c_char,
    group_id_hex: *const c_char,
    endpoints: *const MarmotAppBlobEndpoint,
    endpoints_len: usize,
    out: *mut *mut MarmotSendSummary,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let group_id_hex = try_arg!(unsafe { required_str(group_id_hex) });
        let endpoints = try_arg!(unsafe { struct_array(endpoints, endpoints_len, |e| e.to_ffi()) });
        unsafe {
            deliver(
                client.block_on(client.marmot.replace_encrypted_media_blob_endpoints(
                    account_ref,
                    group_id_hex,
                    endpoints,
                )),
                out,
            )
        }
    })
}

/// Send previously uploaded attachments as one message. Free with
/// `marmot_send_summary_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid; `attachments` must
/// point to `attachments_len` valid caller-owned structs (or be NULL
/// with len 0); `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_send_media_attachments(
    client: *const MarmotClient,
    account_ref: *const c_char,
    group_id_hex: *const c_char,
    attachments: *const MarmotMediaAttachmentReference,
    attachments_len: usize,
    caption: *const c_char,
    out: *mut *mut MarmotSendSummary,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let group_id_hex = try_arg!(unsafe { required_str(group_id_hex) });
        let attachments =
            try_arg!(unsafe { struct_array(attachments, attachments_len, |a| a.to_ffi()) });
        let caption = try_arg!(unsafe { crate::memory::optional_str(caption) });
        unsafe {
            deliver(
                client.block_on(client.marmot.send_media_attachments(
                    account_ref,
                    group_id_hex,
                    attachments,
                    caption,
                )),
                out,
            )
        }
    })
}

/// Send one previously uploaded attachment as a message. Free with
/// `marmot_send_summary_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid; `reference` a valid
/// borrowed struct; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_send_media_reference(
    client: *const MarmotClient,
    account_ref: *const c_char,
    group_id_hex: *const c_char,
    reference: *const MarmotMediaAttachmentReference,
    caption: *const c_char,
    out: *mut *mut MarmotSendSummary,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let group_id_hex = try_arg!(unsafe { required_str(group_id_hex) });
        let reference = try_arg!(unsafe { borrowed(reference) });
        let reference = try_arg!(unsafe { reference.to_ffi() });
        let caption = try_arg!(unsafe { crate::memory::optional_str(caption) });
        unsafe {
            deliver(
                client.block_on(client.marmot.send_media_reference(
                    account_ref,
                    group_id_hex,
                    reference,
                    caption,
                )),
                out,
            )
        }
    })
}

/// Encrypt and upload attachments (optionally sending them). Free with
/// `marmot_media_upload_result_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid; `request` a valid
/// borrowed struct; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_upload_media(
    client: *const MarmotClient,
    account_ref: *const c_char,
    group_id_hex: *const c_char,
    request: *const MarmotMediaUploadRequest,
    out: *mut *mut MarmotMediaUploadResult,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let group_id_hex = try_arg!(unsafe { required_str(group_id_hex) });
        let request = try_arg!(unsafe { borrowed(request) });
        let request = try_arg!(unsafe { request.to_ffi() });
        unsafe {
            deliver(
                client.block_on(
                    client
                        .marmot
                        .upload_media(account_ref, group_id_hex, request),
                ),
                out,
            )
        }
    })
}

/// Download, verify, and decrypt one attachment. Free with
/// `marmot_media_download_result_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid; `reference` a valid
/// borrowed struct; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_download_media(
    client: *const MarmotClient,
    account_ref: *const c_char,
    group_id_hex: *const c_char,
    reference: *const MarmotMediaAttachmentReference,
    out: *mut *mut MarmotMediaDownloadResult,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let group_id_hex = try_arg!(unsafe { required_str(group_id_hex) });
        let reference = try_arg!(unsafe { borrowed(reference) });
        let reference = try_arg!(unsafe { reference.to_ffi() });
        unsafe {
            deliver(
                client.block_on(
                    client
                        .marmot
                        .download_media(account_ref, group_id_hex, reference),
                ),
                out,
            )
        }
    })
}

/// Materialized timeline read. Free the page with
/// `marmot_timeline_page_free`.
///
/// # Safety
/// `client` must be a live handle; `account_ref` a valid string; `query`
/// a valid borrowed struct; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_timeline_messages(
    client: *const MarmotClient,
    account_ref: *const c_char,
    query: *const MarmotTimelineMessageQuery,
    out: *mut *mut MarmotTimelinePage,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let query = try_arg!(unsafe { borrowed(query) });
        let query = try_arg!(unsafe { query.to_ffi() });
        unsafe { deliver(client.marmot.timeline_messages(account_ref, query), out) }
    })
}

/// Register (or update) the account's native push token and share it.
/// `platform` is a `MarmotPushPlatform` discriminant; out-of-range values
/// are rejected with `MARMOT_STATUS_INVALID_ARGUMENT`. Free with
/// `marmot_push_registration_sync_result_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid (`relay_hint`
/// nullable); `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_upsert_push_registration(
    client: *const MarmotClient,
    account_ref: *const c_char,
    platform: u32,
    raw_token: *const c_char,
    server_pubkey_hex: *const c_char,
    relay_hint: *const c_char,
    out: *mut *mut MarmotPushRegistrationSyncResult,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let platform = try_arg!(MarmotPushPlatform::from_c(platform));
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let raw_token = try_arg!(unsafe { required_str(raw_token) });
        let server_pubkey_hex = try_arg!(unsafe { required_str(server_pubkey_hex) });
        let relay_hint = try_arg!(unsafe { crate::memory::optional_str(relay_hint) });
        unsafe {
            deliver(
                client.block_on(client.marmot.upsert_push_registration(
                    account_ref,
                    platform.into(),
                    raw_token,
                    server_pubkey_hex,
                    relay_hint,
                )),
                out,
            )
        }
    })
}

/// Run a bounded background collection pass after a push wake. `source` is
/// a `MarmotNotificationWakeSource` discriminant; out-of-range values are
/// rejected with `MARMOT_STATUS_INVALID_ARGUMENT`. Free with
/// `marmot_background_notification_collection_free`.
///
/// # Safety
/// `client` must be a live handle; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_collect_notifications_after_wake(
    client: *const MarmotClient,
    max_wait_ms: u32,
    source: u32,
    out: *mut *mut MarmotBackgroundNotificationCollection,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let source = try_arg!(MarmotNotificationWakeSource::from_c(source));
        let client = try_arg!(unsafe { client_ref(client) });
        unsafe {
            deliver(
                client.block_on(
                    client
                        .marmot
                        .collect_notifications_after_wake(max_wait_ms, source.into()),
                ),
                out,
            )
        }
    })
}

/// Publish a kind-1200 agent text stream start (anchor) for the group.
/// `stream_id_hex` NULL mints a fresh id; `quic_candidates` are the
/// broker route candidates. Free with `marmot_agent_stream_start_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid; the candidate array
/// must hold `len` valid strings (or be NULL with len 0); `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_start_agent_text_stream(
    client: *const MarmotClient,
    account_ref: *const c_char,
    group_id_hex: *const c_char,
    stream_id_hex: *const c_char,
    quic_candidates: *const *const c_char,
    quic_candidates_len: usize,
    out: *mut *mut MarmotAgentStreamStart,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let group_id_hex = try_arg!(unsafe { required_str(group_id_hex) });
        let stream_id_hex = try_arg!(unsafe { crate::memory::optional_str(stream_id_hex) });
        let quic_candidates = try_arg!(unsafe { str_array(quic_candidates, quic_candidates_len) });
        unsafe {
            deliver(
                client.block_on(client.marmot.start_agent_text_stream(
                    account_ref,
                    group_id_hex,
                    stream_id_hex,
                    quic_candidates,
                )),
                out,
            )
        }
    })
}

/// Encrypt `plaintext` (the raw image bytes, `media_type` e.g.
/// `"image/jpeg"`), upload it to Blossom, and commit it as the group's
/// avatar. Requires admin. The bytes are copied — the caller keeps
/// ownership. Free with `marmot_send_summary_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid; `plaintext` must point
/// to `plaintext_len` valid bytes (or be NULL with length 0); `out`
/// valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_update_group_image(
    client: *const MarmotClient,
    account_ref: *const c_char,
    group_id_hex: *const c_char,
    plaintext: *const u8,
    plaintext_len: usize,
    media_type: *const c_char,
    out: *mut *mut MarmotSendSummary,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let group_id_hex = try_arg!(unsafe { required_str(group_id_hex) });
        let media_type = try_arg!(unsafe { required_str(media_type) });
        let plaintext = try_arg!(unsafe { byte_array(plaintext, plaintext_len) });
        unsafe {
            deliver(
                client.block_on(client.marmot.update_group_image(
                    account_ref,
                    group_id_hex,
                    plaintext,
                    media_type,
                )),
                out,
            )
        }
    })
}

/// Publish the account's kind:0 profile using the account's own relay
/// lists rather than caller-supplied ones. Free with
/// `marmot_user_profile_metadata_free`.
///
/// # Safety
/// `client` must be a live handle; `account_ref` a valid string;
/// `profile` a valid borrowed struct; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_publish_user_profile_using_account_relays(
    client: *const MarmotClient,
    account_ref: *const c_char,
    profile: *const MarmotUserProfileMetadata,
    out: *mut *mut MarmotUserProfileMetadata,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let profile = try_arg!(unsafe { borrowed(profile) });
        let profile = try_arg!(unsafe { profile.to_ffi() });
        unsafe {
            deliver(
                client.block_on(
                    client
                        .marmot
                        .publish_user_profile_using_account_relays(account_ref, profile),
                ),
                out,
            )
        }
    })
}

/// Upload `data` (raw image bytes, `media_type` e.g. `"image/jpeg"`) to
/// Blossom as the account's profile image. `blossom_server` overrides the
/// default server; pass NULL to use it. The bytes are copied — the caller
/// keeps ownership. Writes the image URL; free it with
/// `marmot_string_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid (`blossom_server`
/// nullable); `data` must point to `data_len` valid bytes (or be NULL
/// with length 0); `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_upload_profile_image(
    client: *const MarmotClient,
    account_ref: *const c_char,
    data: *const u8,
    data_len: usize,
    media_type: *const c_char,
    blossom_server: *const c_char,
    out: *mut *mut c_char,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let media_type = try_arg!(unsafe { required_str(media_type) });
        let blossom_server = try_arg!(unsafe { crate::memory::optional_str(blossom_server) });
        let data = try_arg!(unsafe { byte_array(data, data_len) });
        unsafe {
            deliver_string(
                client.block_on(client.marmot.upload_profile_image(
                    account_ref,
                    data,
                    media_type,
                    blossom_server,
                )),
                out,
            )
        }
    })
}

/// Whether this client's storage has been closed (by
/// `marmot_client_shutdown_and_close`). Writes to `out_closed`.
///
/// # Safety
/// `client` must be a live handle; `out_closed` must be valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_storage_is_closed(
    client: *const MarmotClient,
    out_closed: *mut bool,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out(out_closed) });
        let client = try_arg!(unsafe { client_ref(client) });
        let closed = client.marmot.storage_is_closed();
        match unsafe { write_out(out_closed, closed) } {
            Ok(()) => MarmotStatus::Ok,
            Err(status) => status,
        }
    })
}

/// The centralized retired-relay denylist. These hosts must never be
/// dialed or adopted. Free with `marmot_string_list_free`.
///
/// # Safety
/// `client` must be a live handle; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_retired_relay_hosts(
    client: *const MarmotClient,
    out: *mut *mut MarmotStringList,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let hosts = client.marmot.retired_relay_hosts();
        unsafe { deliver(Ok::<_, MarmotKitError>(hosts), out) }
    })
}

/// Store (or replace) the draft for a conversation. `attachments` are
/// copied — the caller keeps ownership of every buffer. Free the result
/// with `marmot_message_draft_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid
/// (`reply_to_message_id_hex` nullable); `attachments` must point to
/// `attachments_len` valid structs (or be NULL with length 0); `out`
/// valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_save_message_draft(
    client: *const MarmotClient,
    account_ref: *const c_char,
    group_id_hex: *const c_char,
    content: *const c_char,
    reply_to_message_id_hex: *const c_char,
    attachments: *const MarmotMessageDraftAttachmentInput,
    attachments_len: usize,
    out: *mut *mut MarmotMessageDraft,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let group_id_hex = try_arg!(unsafe { required_str(group_id_hex) });
        let content = try_arg!(unsafe { required_str(content) });
        let reply_to_message_id_hex =
            try_arg!(unsafe { crate::memory::optional_str(reply_to_message_id_hex) });
        let attachments =
            try_arg!(unsafe { struct_array(attachments, attachments_len, |a| a.to_ffi()) });
        unsafe {
            deliver(
                client.marmot.save_message_draft(
                    account_ref,
                    group_id_hex,
                    content,
                    reply_to_message_id_hex,
                    attachments,
                ),
                out,
            )
        }
    })
}

/// Create a group with the options struct: description, an optional
/// initial avatar, and disappearing-message retention. Writes the new
/// group id as a hex string; free it with `marmot_string_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid; the member array must
/// hold `member_refs_len` valid strings (or be NULL with length 0);
/// `options` a valid borrowed struct; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_create_group_with_options(
    client: *const MarmotClient,
    account_ref: *const c_char,
    name: *const c_char,
    member_refs: *const *const c_char,
    member_refs_len: usize,
    options: *const MarmotCreateGroupOptions,
    out: *mut *mut c_char,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let name = try_arg!(unsafe { required_str(name) });
        let member_refs = try_arg!(unsafe { str_array(member_refs, member_refs_len) });
        let options = try_arg!(unsafe { borrowed(options) });
        let options = try_arg!(unsafe { options.to_ffi() });
        unsafe {
            deliver_string(
                client.block_on(client.marmot.create_group_with_options(
                    account_ref,
                    name,
                    member_refs,
                    options,
                )),
                out,
            )
        }
    })
}

/// `marmot_create_group_with_options` plus the new chat-list row in one
/// round trip. Free with `marmot_created_group_free`.
///
/// # Safety
/// Same as `marmot_create_group_with_options`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_create_group_with_options_detailed(
    client: *const MarmotClient,
    account_ref: *const c_char,
    name: *const c_char,
    member_refs: *const *const c_char,
    member_refs_len: usize,
    options: *const MarmotCreateGroupOptions,
    out: *mut *mut MarmotCreatedGroup,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let name = try_arg!(unsafe { required_str(name) });
        let member_refs = try_arg!(unsafe { str_array(member_refs, member_refs_len) });
        let options = try_arg!(unsafe { borrowed(options) });
        let options = try_arg!(unsafe { options.to_ffi() });
        unsafe {
            deliver(
                client.block_on(client.marmot.create_group_with_options_detailed(
                    account_ref,
                    name,
                    member_refs,
                    options,
                )),
                out,
            )
        }
    })
}

/// Create a group with an inline initial avatar. `initial_image` may be
/// NULL for no image. Writes the new group id as a hex string; free it
/// with `marmot_string_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid (`description`
/// nullable); the member array must hold `member_refs_len` valid strings
/// (or be NULL with length 0); `initial_image` NULL or a valid struct;
/// `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_create_group_with_initial_image(
    client: *const MarmotClient,
    account_ref: *const c_char,
    name: *const c_char,
    member_refs: *const *const c_char,
    member_refs_len: usize,
    description: *const c_char,
    initial_image: *const MarmotInitialGroupImage,
    out: *mut *mut c_char,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let name = try_arg!(unsafe { required_str(name) });
        let member_refs = try_arg!(unsafe { str_array(member_refs, member_refs_len) });
        let description = try_arg!(unsafe { crate::memory::optional_str(description) });
        let initial_image = try_arg!(unsafe { optional_initial_image(initial_image) });
        unsafe {
            deliver_string(
                client.block_on(client.marmot.create_group_with_initial_image(
                    account_ref,
                    name,
                    member_refs,
                    description,
                    initial_image,
                )),
                out,
            )
        }
    })
}

/// `marmot_create_group_with_initial_image` plus the new chat-list row
/// in one round trip. Free with `marmot_created_group_free`.
///
/// # Safety
/// Same as `marmot_create_group_with_initial_image`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_create_group_with_initial_image_detailed(
    client: *const MarmotClient,
    account_ref: *const c_char,
    name: *const c_char,
    member_refs: *const *const c_char,
    member_refs_len: usize,
    description: *const c_char,
    initial_image: *const MarmotInitialGroupImage,
    out: *mut *mut MarmotCreatedGroup,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let name = try_arg!(unsafe { required_str(name) });
        let member_refs = try_arg!(unsafe { str_array(member_refs, member_refs_len) });
        let description = try_arg!(unsafe { crate::memory::optional_str(description) });
        let initial_image = try_arg!(unsafe { optional_initial_image(initial_image) });
        unsafe {
            deliver(
                client.block_on(client.marmot.create_group_with_initial_image_detailed(
                    account_ref,
                    name,
                    member_refs,
                    description,
                    initial_image,
                )),
                out,
            )
        }
    })
}

/// Read a nullable borrowed initial-image struct.
///
/// # Safety
/// `ptr` must be NULL or point to a valid struct.
unsafe fn optional_initial_image(
    ptr: *const MarmotInitialGroupImage,
) -> Result<Option<marmot_uniffi::InitialGroupImageFfi>, MarmotStatus> {
    if ptr.is_null() {
        return Ok(None);
    }
    unsafe { (*ptr).to_ffi() }.map(Some)
}

/// Encrypt and stage a group image without attaching it to a group yet,
/// so the upload can finish before the caller commits to creating one.
/// The bytes are copied — the caller keeps ownership. Free with
/// `marmot_prepared_group_image_upload_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid; `plaintext` must point
/// to `plaintext_len` valid bytes (or be NULL with length 0); `out`
/// valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_stage_prepared_group_image(
    client: *const MarmotClient,
    account_ref: *const c_char,
    plaintext: *const u8,
    plaintext_len: usize,
    media_type: *const c_char,
    out: *mut *mut MarmotPreparedGroupImageUpload,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let media_type = try_arg!(unsafe { required_str(media_type) });
        let plaintext = try_arg!(unsafe { byte_array(plaintext, plaintext_len) });
        unsafe {
            deliver(
                client.block_on(client.marmot.stage_prepared_group_image(
                    account_ref,
                    plaintext,
                    media_type,
                )),
                out,
            )
        }
    })
}

/// Set whether new groups enroll in periodic maintenance.
///
/// # Safety
/// `client` must be a live handle; `account_ref` a valid string.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_set_periodic_maintenance_policy(
    client: *const MarmotClient,
    account_ref: *const c_char,
    policy: u32,
) -> MarmotStatus {
    ffi_guard(|| {
        let policy = try_arg!(MarmotPeriodicMaintenancePolicy::from_c(policy));
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        deliver_unit(
            client.block_on(
                client
                    .marmot
                    .set_periodic_maintenance_policy(account_ref, policy.into()),
            ),
        )
    })
}

/// Build the NIP-92 `imeta` tag for an already-uploaded attachment, so a
/// host can compose the outgoing event itself. Free with
/// `marmot_message_tag_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid; `reference` a valid
/// borrowed struct; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_build_media_imeta_tag(
    client: *const MarmotClient,
    account_ref: *const c_char,
    group_id_hex: *const c_char,
    reference: *const MarmotMediaAttachmentReference,
    out: *mut *mut MarmotMessageTag,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let group_id_hex = try_arg!(unsafe { required_str(group_id_hex) });
        let reference = try_arg!(unsafe { borrowed(reference) });
        let reference = try_arg!(unsafe { reference.to_ffi() });
        unsafe {
            deliver(
                client.block_on(client.marmot.build_media_imeta_tag(
                    account_ref,
                    group_id_hex,
                    reference,
                )),
                out,
            )
        }
    })
}

/// Send a custom application event into the group. `tags` is a flat
/// array of `tags_len` tag rows, each row a `(char **, len)` pair of
/// string values. Free with `marmot_send_summary_free`.
///
/// # Safety
/// `client` must be a live handle; strings valid; `tags` must point to
/// `tags_len` valid rows (or be NULL with length 0), each row's values
/// pointer holding its stated length; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_send_custom_event(
    client: *const MarmotClient,
    account_ref: *const c_char,
    group_id_hex: *const c_char,
    kind: u64,
    tags: *const MarmotStringArray,
    tags_len: usize,
    content: *const c_char,
    out: *mut *mut MarmotSendSummary,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let account_ref = try_arg!(unsafe { required_str(account_ref) });
        let group_id_hex = try_arg!(unsafe { required_str(group_id_hex) });
        let content = try_arg!(unsafe { required_str(content) });
        let tags = try_arg!(unsafe {
            struct_array(tags, tags_len, |row| str_array(row.values, row.values_len))
        });
        unsafe {
            deliver(
                client.block_on(client.marmot.send_custom_event(
                    account_ref,
                    group_id_hex,
                    kind,
                    tags,
                    content,
                )),
                out,
            )
        }
    })
}

/// Classify relay endpoints against the dial-safety and retired-relay
/// policies without dialing any of them. Free with
/// `marmot_relay_endpoint_classification_list_free`.
///
/// # Safety
/// `client` must be a live handle; the endpoint array must hold
/// `endpoints_len` valid strings (or be NULL with length 0); `out`
/// valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_classify_relay_endpoints(
    client: *const MarmotClient,
    endpoints: *const *const c_char,
    endpoints_len: usize,
    out: *mut *mut MarmotRelayEndpointClassificationList,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let endpoints = try_arg!(unsafe { str_array(endpoints, endpoints_len) });
        let classified = client.marmot.classify_relay_endpoints(endpoints);
        unsafe { deliver(Ok::<_, MarmotKitError>(classified), out) }
    })
}

/// Process-wide performance counters. Aggregates only — no account,
/// group, relay, or path information. Free with
/// `marmot_app_performance_snapshot_free`.
///
/// # Safety
/// `client` must be a live handle; `out` valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_app_performance_snapshot(
    client: *const MarmotClient,
    out: *mut *mut MarmotAppPerformanceSnapshot,
) -> MarmotStatus {
    ffi_guard(|| {
        try_arg!(unsafe { crate::preflight_out_ptr(out) });
        let client = try_arg!(unsafe { client_ref(client) });
        let snapshot = client.marmot.app_performance_snapshot();
        unsafe { deliver(Ok::<_, MarmotKitError>(snapshot), out) }
    })
}

/// Record how long a host-side operation took, so it joins the runtime's
/// own timings in `marmot_app_performance_snapshot`. `operation` and
/// `outcome` are discriminants; out-of-range values are rejected with
/// `MARMOT_STATUS_INVALID_ARGUMENT`.
///
/// # Safety
/// `client` must be a live handle.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn marmot_record_host_performance(
    client: *const MarmotClient,
    operation: u32,
    duration_ms: u64,
    outcome: u32,
) -> MarmotStatus {
    ffi_guard(|| {
        let operation = try_arg!(MarmotHostPerformanceOperation::from_c(operation));
        let outcome = try_arg!(MarmotHostPerformanceOutcome::from_c(outcome));
        let client = try_arg!(unsafe { client_ref(client) });
        client
            .marmot
            .record_host_performance(operation.into(), duration_ms, outcome.into());
        MarmotStatus::Ok
    })
}

/// Copy a borrowed `(ptr, len)` byte buffer. `(NULL, 0)` is empty; NULL
/// with a nonzero length is an error.
unsafe fn byte_array(ptr: *const u8, len: usize) -> Result<Vec<u8>, MarmotStatus> {
    if ptr.is_null() {
        if len == 0 {
            return Ok(Vec::new());
        }
        crate::status::set_last_error("byte buffer was NULL with nonzero length");
        return Err(MarmotStatus::NullPointer);
    }
    Ok(unsafe { std::slice::from_raw_parts(ptr, len) }.to_vec())
}

/// Borrow-check a required input-struct pointer.
unsafe fn borrowed<'a, T>(ptr: *const T) -> Result<&'a T, MarmotStatus> {
    if ptr.is_null() {
        crate::status::set_last_error("required struct argument was NULL");
        return Err(MarmotStatus::NullPointer);
    }
    Ok(unsafe { &*ptr })
}

/// Read a borrowed `(ptr, len)` array of input structs through a per-item
/// `to_ffi` conversion. `(NULL, 0)` is empty; NULL with nonzero length is
/// an error.
unsafe fn struct_array<T, F, R>(
    ptr: *const T,
    len: usize,
    convert: F,
) -> Result<Vec<R>, MarmotStatus>
where
    F: Fn(&T) -> Result<R, MarmotStatus>,
{
    if ptr.is_null() {
        if len == 0 {
            return Ok(Vec::new());
        }
        crate::status::set_last_error("struct array was NULL with nonzero length");
        return Err(MarmotStatus::NullPointer);
    }
    let mut out = Vec::with_capacity(len);
    for i in 0..len {
        out.push(convert(unsafe { &*ptr.add(i) })?);
    }
    Ok(out)
}
